### ISSUE TITLE
Conversion panic: `An assertion has failed: invoke must return a promise`

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi-terraform-bridge#1159]
Panic converting https://github.com/terraform-aws-modules/terraform-aws-vpc:

```
pulumi convert --from terraform --language typescript --out pulumi
warning: Plugin converters are currently experimental
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   3.68.1-dev.0
Go Version:       go1.20.4
Go Compiler:      gc
Architecture:     arm64
Operating System: darwin
Panic:            fatal: An assertion has failed: invoke must return a promise

goroutine 1 [running]:
runtime/debug.Stack()
    /opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/debug/stack.go:24 +0x64
main.panicHandler()
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x34
panic({0x106c87d20, 0x14001a0e410})
    /opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/panic.go:884 +0x204
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
    /Users/justin/go/src/github.com/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0xc8?, {0x106572229?, 0x1400c59cf58?}, {0x0?, 0x107172ae0?, 0x1400244dc70?})
    /Users/justin/go/src/github.com/pulumi/pulumi/sdk/go/common/util/contract/assert.go:35 +0xe0
github.com/pulumi/pulumi/pkg/v3/codegen/nodejs.(*generator).awaitInvokes.func1({0x107172860?, 0x14001672880?})
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/nodejs/gen_program_lower.go:239 +0xac
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.visitFunctionCall(0x14001672880, 0x14001672880?, 0x10713a3a0)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:156 +0x110
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.VisitExpression({0x107172860?, 0x14001672880?}, 0x0?, 0x10713a3a0)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:322 +0x134
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.visitRelativeTraversal(0x140015d9cc0, 0x140015d9cc0?, 0x10713a3a0)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:195 +0x40
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.VisitExpression({0x107172d60?, 0x140015d9cc0?}, 0x14001984ec0?, 0x10713a3a0)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:330 +0x1c4
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.visitConditional(0x14000bca2a0, 0x14000bca2a0?, 0x10713a3a0)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:115 +0xdc
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.VisitExpression({0x1071725e0?, 0x14000bca2a0?}, 0x0?, 0x10713a3a0)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:316 +0xc8
github.com/pulumi/pulumi/pkg/v3/codegen/nodejs.(*generator).awaitInvokes(0x0?, {0x1071725e0, 0x14000bca2a0})
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/nodejs/gen_program_lower.go:243 +0x5c
github.com/pulumi/pulumi/pkg/v3/codegen/nodejs.(*generator).lowerExpression(0x1400255fbc0, {0x1071725e0?, 0x14000bca2a0?}, {0x1071731e0, 0x1400167ac40})
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/nodejs/gen_program_expressions.go:30 +0x3c
github.com/pulumi/pulumi/pkg/v3/codegen/nodejs.(*generator).genResourceDeclaration.func1.2()
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/nodejs/gen_program.go:848 +0x30c
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model/format.(*Formatter).Indented(...)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/hcl2/model/format/gen.go:85
github.com/pulumi/pulumi/pkg/v3/codegen/nodejs.(*generator).genResourceDeclaration.func1({0x14001a10d08, 0x17})
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/nodejs/gen_program.go:833 +0x198
github.com/pulumi/pulumi/pkg/v3/codegen/nodejs.(*generator).genResourceDeclaration.func7()
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/nodejs/gen_program.go:988 +0xe0
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model/format.(*Formatter).Indented(...)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/hcl2/model/format/gen.go:85
github.com/pulumi/pulumi/pkg/v3/codegen/nodejs.(*generator).genResourceDeclaration(0x1400255fbc0, {0x1071430c0, 0x140025f6120}, 0x1400194dc30, 0x1)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/nodejs/gen_program.go:986 +0x137c
github.com/pulumi/pulumi/pkg/v3/codegen/nodejs.(*generator).genResource(...)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/nodejs/gen_program.go:1003
github.com/pulumi/pulumi/pkg/v3/codegen/nodejs.(*generator).genNode(0x140093d47e8?, {0x1071430c0?, 0x140025f6120?}, {0x107171f70?, 0x1400194dc30?})
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/nodejs/gen_program.go:684 +0x4c
github.com/pulumi/pulumi/pkg/v3/codegen/nodejs.GenerateProgram.func2()
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/nodejs/gen_program.go:103 +0x68
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model/format.(*Formatter).Indented(...)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/hcl2/model/format/gen.go:85
github.com/pulumi/pulumi/pkg/v3/codegen/nodejs.GenerateProgram(0x1400254da00)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/nodejs/gen_program.go:101 +0x44c
github.com/pulumi/pulumi/pkg/v3/codegen/nodejs.GenerateProject({0x16b1432f4, 0x4b}, {{0x140004d2ae6, 0x11}, {{0x0, 0x0}, 0x0}, {0x0, 0x0}, 0x0, ...}, ...)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/nodejs/gen_program.go:160 +0x34
main.runConvert.func1.1({0x10716dc80, 0x14000c53e60}, {0x1400005e640, 0x48}, {0x16b1432f4, 0x4b}, {0x10715cd68?, 0x14000dc3080?})
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/convert.go:252 +0x1d4
main.runConvert({0x107163860, 0x140003f7400}, {0x140004d2ac0, 0x37}, {0x1083192c8, 0x0, 0x0}, {0x16b1432ce, 0x9}, {0x16b1432e3, ...}, ...)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/convert.go:435 +0x114c
main.newConvertCmd.func1(0x0?, {0x0?, 0x0?, 0x0?})
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/convert.go:75 +0x170
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0x14000dae300?, {0x14000da48a0, 0x0, 0x6})
    /Users/justin/go/src/github.com/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x38
github.com/spf13/cobra.(*Command).execute(0x14000dae300, {0x14000da4840, 0x6, 0x6})
    /Users/justin/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x5b0
github.com/spf13/cobra.(*Command).ExecuteC(0x14000974c00)
    /Users/justin/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
    /Users/justin/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x3c
```

**Comment by justinvp** [comment]
Fixed by https://github.com/pulumi/pulumi/pull/13085
