### ISSUE TITLE
Conversion panic: `An assertion has failed: invoke should return a promise, got output(object({result = string}`

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi-terraform-bridge#1161]
Panic converting https://github.com/terraform-aws-modules/terraform-aws-vpc to C#:

```
pulumi convert --from terraform --language c# --out pulumicsharp
warning: Plugin converters are currently experimental
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   3.68.1-dev.0
Go Version:       go1.20.4
Go Compiler:      gc
Architecture:     arm64
Operating System: darwin
Panic:            fatal: An assertion has failed: invoke should return a promise, got output(object({result = string}, annotated(0x1400312be00)))

goroutine 1 [running]:
runtime/debug.Stack()
    /opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/debug/stack.go:24 +0x64
main.panicHandler()
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x34
panic({0x104cf3d20, 0x140018d2be0})
    /opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/panic.go:884 +0x204
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
    /Users/justin/go/src/github.com/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0x0?, {0x104601d3c?, 0x1400cc0cd58?}, {0x1400cc0cd48?, 0x1400cc0ce08?, 0x0?})
    /Users/justin/go/src/github.com/pulumi/pulumi/sdk/go/common/util/contract/assert.go:35 +0xe0
github.com/pulumi/pulumi/pkg/v3/codegen/dotnet.(*generator).awaitInvokes.func1({0x1051de860?, 0x14000d65d00?})
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/dotnet/gen_program_expressions.go:86 +0xcc
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.visitFunctionCall(0x14000d65d00, 0x14000d65d00?, 0x1051a62e0)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:156 +0x110
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.VisitExpression({0x1051de860?, 0x14000d65d00?}, 0x1051de660?, 0x1051a62e0)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:322 +0x134
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.visitExpressions({0x140018d2700, 0x1, 0x1}, 0x1400184dba0?, 0x0?)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:272 +0xb8
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.visitFunctionCall(0x140032d1a00, 0x140032d1a00?, 0x1051a62e0)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:151 +0x48
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.VisitExpression({0x1051de860?, 0x140032d1a00?}, 0x1051dede0?, 0x1051a62e0)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:322 +0x134
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.visitAnonymousFunction(0x14001964480, 0x14001964480?, 0x1051a62e0)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:85 +0x40
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.VisitExpression({0x1051de4e0?, 0x14001964480?}, 0x0?, 0x1051a62e0)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:312 +0x80
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.visitExpressions({0x14002f52ca0, 0x2, 0x2}, 0x10421dc98?, 0x14000d65c80?)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:272 +0xb8
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.visitFunctionCall(0x140032d1480, 0x140032d1480?, 0x1051a62e0)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:151 +0x48
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.VisitExpression({0x1051de860?, 0x140032d1480?}, 0x1400cc0d498?, 0x1051a62e0)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:322 +0x134
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.visitExpressions({0x14002f52d60, 0x2, 0x2}, 0x10421bcfc?, 0x1051de9e0?)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:272 +0xb8
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.visitFunctionCall(0x140032d1580, 0x140032d1580?, 0x1051a62e0)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:151 +0x48
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.VisitExpression({0x1051de860?, 0x140032d1580?}, 0x1051de560?, 0x1051a62e0)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:322 +0x134
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.visitExpressions({0x140018d2780, 0x1, 0x1}, 0x0?, 0x0?)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:272 +0xb8
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.visitFunctionCall(0x140032d1a80, 0x140032d1a80?, 0x1051a62e0)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:151 +0x48
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.VisitExpression({0x1051de860?, 0x140032d1a80?}, 0x1400cc0d908?, 0x1051a62e0)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:322 +0x134
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.visitConditional(0x14000c062a0, 0x14000c062a0?, 0x1051a62e0)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:115 +0xdc
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.VisitExpression({0x1051de5e0?, 0x14000c062a0?}, 0x0?, 0x1051a62e0)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:316 +0xc8
github.com/pulumi/pulumi/pkg/v3/codegen/dotnet.(*generator).awaitInvokes(0x1051de5e0?, {0x1051de5e0, 0x14000c062a0})
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/dotnet/gen_program_expressions.go:90 +0x5c
github.com/pulumi/pulumi/pkg/v3/codegen/dotnet.(*generator).rewriteExpression(0x140019cba40, {0x1051de5e0?, 0x14000c062a0?}, {0x1051df1e0, 0x14003121640}, 0x1)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/dotnet/gen_program_expressions.go:48 +0x14c
github.com/pulumi/pulumi/pkg/v3/codegen/dotnet.(*generator).lowerExpression(...)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/dotnet/gen_program_expressions.go:59
github.com/pulumi/pulumi/pkg/v3/codegen/dotnet.(*generator).genResource(0x140019cba40, {0x1051af0c0, 0x1400223fe60}, 0x140019dd970)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/dotnet/gen_program.go:1149 +0x260
github.com/pulumi/pulumi/pkg/v3/codegen/dotnet.(*generator).genNode(0x140019cba40?, {0x1051af0c0?, 0x1400223fe60?}, {0x1051ddf70?, 0x140019dd970?})
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/dotnet/gen_program.go:825 +0x44
github.com/pulumi/pulumi/pkg/v3/codegen/dotnet.GenerateProgramWithOptions.func1(...)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/dotnet/gen_program.go:146
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model/format.(*Formatter).Indented(...)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/hcl2/model/format/gen.go:85
github.com/pulumi/pulumi/pkg/v3/codegen/dotnet.GenerateProgramWithOptions(0x14002205dc0, {0xa8?})
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/dotnet/gen_program.go:144 +0x608
github.com/pulumi/pulumi/pkg/v3/codegen/dotnet.GenerateProgram(0x1400328a2c0?)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/dotnet/gen_program.go:230 +0x20
github.com/pulumi/pulumi/pkg/v3/codegen/dotnet.GenerateProject({0x16d0d72f4, 0x4b}, {{0x14000242f26, 0x11}, {{0x0, 0x0}, 0x0}, {0x0, 0x0}, 0x0, ...}, ...)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/codegen/dotnet/gen_program.go:234 +0x34
main.runConvert.func1.1({0x1051d9c80, 0x14000bcfe30}, {0x1400005eb40, 0x49}, {0x16d0d72f4, 0x4b}, {0x1051c8d68?, 0x14000c41080?})
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/convert.go:252 +0x1d4
main.runConvert({0x1051cf860, 0x14000249b70}, {0x14000242f00, 0x37}, {0x1063852c8, 0x0, 0x0}, {0x16d0d72d6, 0x9}, {0x16d0d72eb, ...}, ...)
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/convert.go:435 +0x114c
main.newConvertCmd.func1(0x0?, {0x0?, 0x0?, 0x0?})
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/convert.go:75 +0x170
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0x14000c22300?, {0x14000c1a780, 0x0, 0x6})
    /Users/justin/go/src/github.com/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x38
github.com/spf13/cobra.(*Command).execute(0x14000c22300, {0x14000c1a720, 0x6, 0x6})
    /Users/justin/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x5b0
github.com/spf13/cobra.(*Command).ExecuteC(0x1400064ac00)
    /Users/justin/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
    /Users/justin/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
    /Users/justin/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x3c
```

**Comment by justinvp** [comment]
Related to https://github.com/pulumi/pulumi-terraform-bridge/issues/1159?

**Comment by justinvp** [comment]
Fixed by https://github.com/pulumi/pulumi/pull/13092
