### ISSUE TITLE
Conversion panic: `invalid memory address or nil pointer dereference`

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi-terraform-bridge#1177]
Panic converting the following examples to Go:

- https://github.com/philips-labs/terraform-aws-github-runner
- https://github.com/aws-samples/hub-and-spoke-with-inspection-vpc-terraform
- https://github.com/aws-ia/terraform-aws-eks-blueprints/examples/multi-tenancy-with-teams

```
pulumi convert --from terraform --language go --out pulumigo

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x100cc0340]

goroutine 41 [running]:

github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.HclDiagnosticToRPCDiagnostic(0x140006f1500)
    /Users/justin/go/src/github.com/pulumi/pulumi/sdk/go/common/resource/plugin/langruntime_plugin.go:509 +0xb0
main.(*goLanguageHost).GenerateProject(0x140000a05a0, {0x100c3c98c?, 0x40?}, 0x1400012e180)
    /Users/justin/go/pkg/mod/github.com/pulumi/pulumi/sdk/go/pulumi-language-go/v3@v3.0.0-20230602090130-5a53aa01dc2f/main.go:838 +0x3e0
github.com/pulumi/pulumi/sdk/v3/proto/go._LanguageRuntime_GenerateProject_Handler.func1({0x102312310, 0x140009e4780}, {0x1021a6320?, 0x1400012e180})
    /Users/justin/go/src/github.com/pulumi/pulumi/sdk/proto/go/language_grpc.pb.go:429 +0x74
github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x102312310, 0x140009e4120}, {0x1021a6320, 0x1400012e180}, 0x1400031e5c0, 0x1400042c348)
    /Users/justin/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x308
github.com/pulumi/pulumi/sdk/v3/proto/go._LanguageRuntime_GenerateProject_Handler({0x10224cfc0?, 0x140000a05a0}, {0x102312310, 0x140009e4120}, 0x140006ca000, 0x14000a91d60)
    /Users/justin/go/src/github.com/pulumi/pulumi/sdk/proto/go/language_grpc.pb.go:431 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0x140004dc1e0, {0x10231afe0, 0x14000331520}, 0x140004dbe60, 0x140007c2720, 0x103174790, 0x0)
    /Users/justin/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:1345 +0xc90
google.golang.org/grpc.(*Server).handleStream(0x140004dc1e0, {0x10231afe0, 0x14000331520}, 0x140004dbe60, 0x0)
    /Users/justin/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:1722 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
    /Users/justin/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:966 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
    /Users/justin/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:964 +0x28c
error: could not generate output program: error reading from server: EOF
```

**Comment by justinvp** [comment]
Fixed by https://github.com/pulumi/pulumi/pull/13084
