### ISSUE TITLE
 panic: HasAttribute on non-object Type

### ISSUE THREAD

**Issue by dirien** [pulumi/pulumi-terraform-bridge#1231]
### What happened?

While setting up a Scaleway Redis Cluster, I get this error message during `pulumi up` in the preview phase:

```bash
Diagnostics:
  pulumi:pulumi:Stack (test-scaleway-ts-dev):
    panic: HasAttribute on non-object Type
    goroutine 55 [running]:
    github.com/hashicorp/go-cty/cty.Type.HasAttribute({{0x0?, 0x0?}}, {0x101630eeb?, 0x12a67e4c8?})
        /home/runner/go/pkg/mod/github.com/hashicorp/go-cty@v1.4.1-0.20200414143053-d3edf31b6320/cty/object_type.go:104 +0x94
    github.com/scaleway/terraform-provider-scaleway/v2/scaleway.getLocality(0x14000a64e08?, 0x10077d084?)
        /home/runner/go/pkg/mod/github.com/scaleway/terraform-provider-scaleway/v2@v2.21.0/scaleway/helpers.go:915 +0x3c
    github.com/scaleway/terraform-provider-scaleway/v2/scaleway.customizeDiffLocalityCheck.func1({0x101e46398?, 0x14000196018?}, 0x10163f522?, {0x101b77c00?, 0x14000383a70?})
        /home/runner/go/pkg/mod/github.com/scaleway/terraform-provider-scaleway/v2@v2.21.0/scaleway/helpers.go:932 +0x58
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0x14000874510, {0x101e46398, 0x14000196018}, 0x14000aac0d0, 0x14000a8b260, 0x140005971e0, {0x101b77c00, 0x14000383a70}, 0x0)
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230327102345-3fa930f86570/helper/schema/schema.go:699 +0x3bc
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0x0?, {0x101e46398?, 0x14000196018?}, 0x14000aac0d0, 0x14000a65378?, {0x101b77c00?, 0x14000383a70?})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230327102345-3fa930f86570/helper/schema/resource.go:895 +0x50
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.simpleDiff({0x101c2aa80?, {0x140003f0f30?, 0x10164fba2?, 0x16?}}, 0x0?, 0xffffffffffffffff?, 0x14000aac000, 0x1010aa1d0?, {{{0x101e47240?, 0x140001aaff0?}}, ...}, ...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.49.1/pkg/tfshim/sdk-v2/provider_diff.go:87 +0x5dc
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Diff({0x1400008c2a0?, {0x0?, 0x0?, 0x14000a65688?}}, {0x10164fba2, 0x16}, {0x0?, 0x0}, {0x101e3d6e0, 0x14000a8b260})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.49.1/pkg/tfshim/sdk-v2/provider_diff.go:63 +0x210
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Create(0x140001f0500, {0x101e46408?, 0x14000a8b020?}, 0x14000a886e0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.49.1/pkg/tfbridge/provider.go:725 +0x2d0
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler.func1({0x101e46408, 0x14000a8b020}, {0x101d631a0?, 0x14000a886e0})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.69.0/proto/go/provider_grpc.pb.go:573 +0x74
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x101e46408, 0x14000a8acc0}, {0x101d631a0, 0x14000a886e0}, 0x140004f08a0, 0x140004f8360)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x30c
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler({0x101df3de0?, 0x140001f0500}, {0x101e46408, 0x14000a8acc0}, 0x14000125c00, 0x14000714be0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.69.0/proto/go/provider_grpc.pb.go:575 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0x140009fe000, {0x101e4da20, 0x14000183040}, 0x1400081de60, 0x140009e9fb0, 0x102a8e160, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:1345 +0xc64
    google.golang.org/grpc.(*Server).handleStream(0x140009fe000, {0x101e4da20, 0x14000183040}, 0x1400081de60, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:1722 +0x82c
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:966 +0x84
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:964 +0x290

    error: preview failed

  scaleway:index:RedisCluster (devopsdaysams-redis):
    error: Preview failed: error reading from server: EOF
```

### Expected Behavior

No error!

### Steps to reproduce

Use this TS code:

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as scaleway from "@lbrlabs/pulumi-scaleway";


const redis = new scaleway.RedisCluster("devopsdaysams-redis", {
    name: "devopsdaysams-redis",
    userName: "devopsdaysams",
    password: "Devopsdaysams1!",
    nodeType: "RED1-micro",
    version: "7.0.5",
    clusterSize: 1,
    acls: [
        {
            ip: "0.0.0.0/0",
            description: "Allow all",
        }
    ],
});


export const redisName = redis.name;
```

### Output of `pulumi about`

```bash
pulumi about
CLI          
Version      3.72.2
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME      VERSION
nodejs    unknown
scaleway  1.9.0

Host     
OS       darwin
Version  12.6.3
Arch     arm64

This project is written in nodejs: executable='/Users/dirien/.nvm/versions/node/v18.14.0/bin/node' version='v18.14.0'

Current Stack: dirien/test-scaleway-ts/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/dirien


Dependencies:
NAME                      VERSION
@lbrlabs/pulumi-scaleway  1.9.0
@pulumi/pulumi            3.72.1
@types/node               16.18.36

Pulumi locates its logs in /var/folders/tv/ccfx977s0f3934vn0wcm5d7c0000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Thanks so much, awesome to have a repro. Going to have a look.

**Comment by benjick** [comment]
I'm getting this error with the following code:

```ts
const mainDatabaseInstance = new scaleway.DatabaseInstance(
  "mainDatabaseInstance",
  {
    nodeType: "DB-DEV-S",
    engine: "PostgreSQL-11",
    isHaCluster: true,
    disableBackup: true,
    userName: "my_initial_user",
    password: "thiZ_is_v&ry_s3cret",
  },
);
```
