### ISSUE TITLE
SIGSEGV in tfbridge.parseCheckError

### ISSUE THREAD

**Issue by zhangyoufu** [pulumi/pulumi-terraform-bridge#1368]
This bug was triggered during `pulumi import`.

```
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x84797bf]
    goroutine 23 [running]:
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.parseCheckError({0xae3bf28, 0xc0001b56b0}, 0xc001fd3a70?, {0xae07880?, 0xc003148f10})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.59.0/pkg/tfbridge/adapt_check_failures.go:94 +0x31f
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).adaptCheckFailures(0xc0008a8000, {0x9ec1edc?, 0xd40010?}, {0xc0010dd340, 0x3e}, 0x0?, {0xae3bf28, 0xc0001b56b0}, 0x0?, {0xc003114800, ...})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.59.0/pkg/tfbridge/adapt_check_failures.go:46 +0x113
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Check(0xc0008a8000, {0xae353f0?, 0xc003108fc0?}, 0xc000ca7680)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.59.0/pkg/tfbridge/provider.go:599 +0x925
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Check_Handler.func1({0xae353f0, 0xc003108fc0}, {0x9417220?, 0xc000ca7680})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.81.0/proto/go/provider_grpc.pb.go:537 +0x72
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0xae353f0, 0xc003108ea0}, {0x9417220, 0xc000ca7680}, 0xc0031145c0, 0xc000c1ea38)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3d0
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Check_Handler({0x9723440?, 0xc0008a8000}, {0xae353f0, 0xc003108ea0}, 0xc003128540, 0xc00073a780)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.81.0/proto/go/provider_grpc.pb.go:539 +0x135
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000fe6000, {0xae8f3e0, 0xc001346680}, 0xc0031237a0, 0xc0020246c0, 0x131fb3d0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1360 +0xe15
    google.golang.org/grpc.(*Server).handleStream(0xc000fe6000, {0xae8f3e0, 0xc001346680}, 0xc0031237a0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1737 +0x9e7
    google.golang.org/grpc.(*Server).serveStreams.func1.1()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:982 +0x8d
    created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 72
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:980 +0x165

    error: preview failed
```

related code:
https://github.com/pulumi/pulumi-terraform-bridge/blob/ca7fd3a6261828e23280232800ddeec36b46df2e/pkg/tfbridge/adapt_check_failures.go#L80-L94

When `errors.As(err, &d)` returns `false`, `d` is unset and inlined `d.Error()` panic due to `e.Detail` deference a nil pointer.

**Comment by zhangyoufu** [comment]
> @zhangyoufu Thank you for filing this issue and sorry for the trouble! Could you please specify which import command I can run to reproduce this issue?

This can be reproduced in a brand-new pulumi project, trying to import alicloud VPC vSwitch resource.

```
% pulumi import alicloud:vpc/switch:Switch resource-name vsw-XXXXXXXXXXXXXXXXXXXXX
Previewing import (dev):
     Type                    Name            Plan       Info
 +   pulumi:pulumi:Stack     reproducer-dev  create     1 error; 23 messages
 =   └─ alicloud:vpc:Switch  resource-name   import     1 error; 2 warnings


Diagnostics:
  pulumi:pulumi:Stack (reproducer-dev):
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x84797bf]
    goroutine 63 [running]:
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.parseCheckError({0xae3bf28, 0xc001214900}, 0x9f12787?, {0xae07880?, 0xc0019f7580})
      /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.59.0/pkg/tfbridge/adapt_check_failures.go:94 +0x31f
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).adaptCheckFailures(0xc00069a580, {0x9ec1edc?, 0x0?}, {0xc002665540, 0x45}, 0x50?, {0xae3bf28, 0xc001214900}, 0x0?, {0xc0026755c0, ...})
      /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.59.0/pkg/tfbridge/adapt_check_failures.go:46 +0x113
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Check(0xc00069a580, {0xae353f0?, 0xc00272ac60?}, 0xc000c81800)
      /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.59.0/pkg/tfbridge/provider.go:599 +0x925
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Check_Handler.func1({0xae353f0, 0xc00272ac60}, {0x9417220?, 0xc000c81800})
      /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.81.0/proto/go/provider_grpc.pb.go:537 +0x72
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0xae353f0, 0xc00272ab40}, {0x9417220, 0xc000c81800}, 0xc002675380, 0xc0028c50b0)
      /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3d0
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Check_Handler({0x9723440?, 0xc00069a580}, {0xae353f0, 0xc00272ab40}, 0xc0027207e0, 0xc0009fa7e0)
      /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.81.0/proto/go/provider_grpc.pb.go:539 +0x135
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc002730000, {0xae8f3e0, 0xc000d0c1a0}, 0xc00046c480, 0xc0028c9380, 0x131fb3d0, 0x0)
      /home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1360 +0xe15
    google.golang.org/grpc.(*Server).handleStream(0xc002730000, {0xae8f3e0, 0xc000d0c1a0}, 0xc00046c480, 0x0)
      /home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1737 +0x9e7
    google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:982 +0x8d
    created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 25
      /home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:980 +0x165

    error: preview failed

  alicloud:vpc:Switch (resource-name):
    warning: urn:pulumi:dev::reproducer::alicloud:vpc/switch:Switch::resource-name verification warning: "name": [DEPRECATED] Field 'name' has been deprecated from provider version 1.119.0. New field 'vswitch_name' instead.
    warning: urn:pulumi:dev::reproducer::alicloud:vpc/switch:Switch::resource-name verification warning: "availability_zone": [DEPRECATED] Field 'availability_zone' has been deprecated from provider version 1.119.0. New field 'zone_id' instead.
    error: Preview failed: error reading from server: EOF
```

**Comment by zhangyoufu** [comment]
I also checked that `terraform import` works without problem.

**Comment by mikhailshilkov** [comment]
I fixed the panic in the bridge, I'll update the issue when we release it in AWS
