### ISSUE TITLE
Flaky test with DLL32 loading issue on Windows

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#1437]
### What happened?

```
=== NAME  TestAccProviderConfig
    command.go:83: Invoke 'C:\ProgramData\chocolatey\lib\pulumi\tools\Pulumi\bin\pulumi.exe stack export --file C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az417-3-provider-c-c0c95d023789257115\stack.json' failed: exit status 2
panic: Failed to load user32: A dynamic link library (DLL) initialization routine failed.

goroutine 1 [running]:
syscall.MustLoadDLL(...)
	/opt/hostedtoolcache/go/1.21.1/x64/src/syscall/dll_windows.go:94
github.com/atotto/clipboard.init()
	/home/runner/go/pkg/mod/github.com/atotto/clipboard@v0.1.4/clipboard_windows.go:22 +0x347

    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az417-3-provider-c-c0c95d02-1541851738\command-output\pulumi-export.20231012-180950.a95cd.log
    program.go:1335: Destroying stack
    command.go:34: **** Invoke 'C:\ProgramData\chocolatey\lib\pulumi\tools\Pulumi\bin\pulumi.exe destroy --non-interactive --yes --skip-preview' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az417-3-provider-c-c0c95d02-1541851738'
    command.go:83: Invoke 'C:\ProgramData\chocolatey\lib\pulumi\tools\Pulumi\bin\pulumi.exe destroy --non-interactive --yes --skip-preview' failed: exit status 2
panic: Failed to load user32: A dynamic link library (DLL) initialization routine failed.
```

Might be a good idea to find out why Pulumi CLI is initializing clipboard. 

### Example

Found during CI runs.

### Output of `pulumi about`

v3.86.0

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Should the issue go to pulumi/pulumi?

**Comment by t0yv0** [comment]
Yeah good point, let me move. I think I'm less worried about the flaky test and the fact that it might blow up on customer machines.
