### ISSUE TITLE
ListNestedObjectTypeOf[...] is not supported for blocks

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#1523]
### What happened?

When performing AWS upgrade to v5.25.0 tfgen started failing with:

```
panic: block.Type()==ListNestedObjectTypeOf[resourceexplorer2.searchFilterModel] is not supported for blocks

goroutine 1 [running]:
github.com/pulumi/pulumi-terraform-bridge/pf/internal/schemashim.(*blockSchema).Elem(0xc008981240)
        /Users/t0yv0/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.18.4-0.20231103010134-1e955db434c6/internal/schemashim/block_schema.go:91 +0x1e7
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.applyMaxItemsOneAliasing({0x115f8780, 0xc008981240}, 0xc00732e3c0, 0xc008f78340)
        /Users/t0yv0/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.63.3-0.20231103010134-1e955db434c6/pkg/tfbridge/auto_aliasing.go:356 +0x21b
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.applyResourceMaxItemsOneAliasing.func1({0xfe7b636, 0x7}, {0x115f8780, 0xc008981240})
        /Users/t0yv0/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.63.3-0.20231103010134-1e955db434c6/pkg/tfbridge/auto_aliasing.go:240 +0xa5
github.com/pulumi/pulumi-terraform-bridge/pf/internal/schemashim.(*schemaMap).Range(0xc00221aa50, 0xc008f61b30)
        /Users/t0yv0/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.18.4-0.20231103010134-1e955db434c6/internal/schemashim/schema_map.go:90 +0x594
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.applyResourceMaxItemsOneAliasing({0x115cfae0?, 0xc0024393d0?}, 0xc006d1b9b0, 0xc00273e4e0)
        /Users/t0yv0/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.63.3-0.20231103010134-1e955db434c6/pkg/tfbridge/auto_aliasing.go:237 +0xf9
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.aliasResource(0xc00249c240, {0x115cfae0, 0xc0024393d0}, 0xc009786530, 0xc0097864c8?, 0xc00273e4d0, {0xff59266, 0x1a}, 0x6)        /Users/t0yv0/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.63.3-0.20231103010134-1e955db434c6/pkg/tfbridge/auto_aliasing.go:220 +0x39a
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*ProviderInfo).ApplyAutoAliases(0xc00249c240)
        /Users/t0yv0/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.63.3-0.20231103010134-1e955db434c6/pkg/tfbridge/auto_aliasing.go:141 +0x248
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*ProviderInfo).MustApplyAutoAliases(0xc00249c240?)
        /Users/t0yv0/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.63.3-0.20231103010134-1e955db434c6/pkg/tfbridge/auto_aliasing.go:85 +0x13
github.com/pulumi/pulumi-aws/provider/v6.Provider()
        /Users/t0yv0/code/pulumi-aws/provider/resources.go:7225 +0x75b45
main.main()
        /Users/t0yv0/code/pulumi-aws/provider/cmd/pulumi-tfgen-aws/main.go:24 +0x34
make: *** [tfgen] Error 2
```

It looks like there's some remaining cases in Plugin Framework schema discovery that are not yet supported.

### Example

See https://github.com/pulumi/pulumi-aws/pull/2998

### Output of `pulumi about`

N/A

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Looks like it is a custom type implementing the following interfaces:

```
	_ basetypes.ListTypable  = (*listNestedObjectTypeOf[struct{}])(nil)
	_ NestedObjectType       = (*listNestedObjectTypeOf[struct{}])(nil)
	_ basetypes.ListValuable = (*ListNestedObjectValueOf[struct{}])(nil)
	_ NestedObjectValue      = (*ListNestedObjectValueOf[struct{}])(nil)
```

Our schema parser only recognizes concrete types currently, might need to be generalized to accept custom types by interface, or find some other way to excract the schema.

**Comment by t0yv0** [comment]
Fixed by https://github.com/pulumi/pulumi-terraform-bridge/pull/1525
