### ISSUE TITLE
Community provider panics at runtime with unmapped resources

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-terraform-bridge#1838]
### What happened?

See https://github.com/pulumi/registry/pull/3898#issue-2116688091 for an explanation

### Example

☝️

### Output of `pulumi about`

NA

### Additional context

My guess is we are trying to name the resources and panicking because they don't have the expected prefix. We'll know more when we see a stack trace.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by a-schot** [comment]
Hey, thanks for opening an issue for this! 

I created a [new branch](https://github.com/a-schot/pulumi-dbtcloud/tree/reproduce-prefix-panic) to reproduce the panic. Only thing I did is remove the explicit mappings for `Legacy*` resources/datasources.

Stack trace when running `pulumi preview` in `examples/project/py`:

```
 pulumi:providers:dbtcloud (default_0_0_0_github_/api.github.com/a-schot/pulumi-dbtcloud):
    error: could not read plugin [/workspaces/pulumi-dbtcloud/bin/pulumi-resource-dbtcloud] stdout: EOF

  pulumi:pulumi:Stack (py-dev):
    panic: fatal: An assertion has failed: Expected all Terraform resources in this module to have a 'dbtcloud_' prefix
    goroutine 1 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /root/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.105.0/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0x90?, {0x130e328?, 0x0?}, {0xc00069ea00?, 0x0?, 0x0?})
        /root/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.105.0/go/common/util/contract/assert.go:35 +0xe8
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).camelPascalPulumiName(0x10fdc40?, {0x12dcc6e, 0x17})
        /root/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.72.0/pkg/tfbridge/provider.go:373 +0x119
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).initResourceMaps.func1({0x12dcc6e, 0x17}, {0x14e7ae0, 0xc00012d180})
        /root/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.72.0/pkg/tfbridge/provider.go:325 +0xc5
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2ResourceMap.Range(0x412465?, 0xc0005bde80)
        /root/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.72.0/pkg/tfshim/sdk-v2/resource.go:149 +0x8b
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).initResourceMaps(0xc000381980)
        /root/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.72.0/pkg/tfbridge/provider.go:310 +0xa8
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.newProvider({_, _}, _, {_, _}, {_, _}, {_, _}, {{0x14f0f60, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.72.0/pkg/tfbridge/provider.go:212 +0x231
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.NewProvider({_, _}, _, {_, _}, {_, _}, {_, _}, {{0x14f0f60, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.72.0/pkg/tfbridge/provider.go:196 +0xce
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.Main.Serve.func1(0xc0001bedc0?)
        /root/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.72.0/pkg/tfbridge/serve.go:29 +0x130
    github.com/pulumi/pulumi/pkg/v3/resource/provider.Main.func2(0xc000368c00)
        /root/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.105.0/resource/provider/main.go:79 +0x2a
    github.com/pulumi/pulumi/sdk/v3/go/common/util/rpcutil.serveWithOptions({0x0, 0xc0005ac588, 0xc0004796e0, {0xc0005f3360, 0x2, 0x2}})
        /root/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.105.0/go/common/util/rpcutil/serve.go:93 +0x304
    github.com/pulumi/pulumi/sdk/v3/go/common/util/rpcutil.ServeWithOptions(...)
        /root/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.105.0/go/common/util/rpcutil/serve.go:72
    github.com/pulumi/pulumi/pkg/v3/resource/provider.Main({0x12ca918, 0x8}, 0xc0000bed70)
        /root/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.105.0/resource/provider/main.go:76 +0x405
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.Serve(...)
        /root/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.72.0/pkg/tfbridge/serve.go:28
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.Main({_, _}, {_, _}, {{0x14f0f60, 0xc0005f2880}, {0x12ca918, 0x8}, {0x0, 0x0}, ...}, ...)
        /root/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.72.0/pkg/tfbridge/main.go:73 +0x4d1
    main.main()
        /workspaces/pulumi-dbtcloud/provider/cmd/pulumi-resource-dbtcloud/main.go:32 +0xca

    warning: using pulumi-resource-dbtcloud from $PATH at /workspaces/pulumi-dbtcloud/bin/pulumi-resource-dbtcloud
    warning: using pulumi-resource-dbtcloud from $PATH at /workspaces/pulumi-dbtcloud/bin/pulumi-resource-dbtcloud
```
