### ISSUE TITLE
PlanResourceChange State Upgrade panics

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#1966]
### What happened?

panic in pulumi-docker: https://github.com/pulumi/pulumi-docker/actions/runs/9065201571/job/24905969782?pr=1095 - `nil not []interface{}`
also in pulumi-gitlab: https://github.com/pulumi/pulumi-gitlab/actions/runs/9065318227/job/24906511390?pr=598
- `nil not string`

a bunch of panics in pulumi-azure: https://github.com/pulumi/pulumi-azure/actions/runs/9065375778/job/24907714741?pr=2030

### Example

```
Diagnostics:
    docker:index:Service (service):
      error: error reading from server: EOF
  
    pulumi:pulumi:Stack (swarm-service-p-it-fv-az1052--service-1d85caa0):
      panic: interface conversion: interface {} is nil, not []interface {}
      goroutine 57 [running]:
      github.com/terraform-providers/terraform-provider-docker/internal/provider.resourceDockerServiceStateUpgradeV2({0xa10000c0004a3088?, 0x41f836?}, 0x2?, {0xc000124ff0?, 0x412485?})
      	/home/runner/work/pulumi-docker/pulumi-docker/upstream/internal/provider/resource_docker_service_migrators.go:10 +0x36d
      github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.UpgradeJSONState({0x195b7e8, 0xc000297e00}, 0x0?, 0xc00061d260?, 0xc0005dec40?, {0x13b0e20, 0xc000522150})
      	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-202[402](https://github.com/pulumi/pulumi-docker/actions/runs/9065201571/job/24905969782?pr=1095#step:27:414)29143312-4f60ee4e2975/helper/schema/grpc_provider.go:491 +0x70
      github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.upgradeResourceState({0x195b7e8, 0xc000297e00}, 0xc000608cc0, 0x0?, 0xc00063d380)
      	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.82.1-0.202[405](https://github.com/pulumi/pulumi-docker/actions/runs/9065201571/job/24905969782?pr=1095#step:27:417)13144526-3242c866b548/pkg/tfshim/sdk-v2/upgrade_state.go:45 +0x207
      github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.(*planResourceChangeImpl).upgradeState(0xc000795320, {0x195b7e8, 0xc000297e00}, {0x16df8d6, 0xe}, {0x0, 0x0})
      	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.82.1-0.20240513144526-3242c866b548/pkg/tfshim/sdk-v2/provider2.go:334 +0x149
      github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.(*planResourceChangeImpl).Diff(0xc000795320, {0x195b7e8, 0xc000297e00}, {0x16df8d6, 0xe}, {0x0?, 0x0?}, {0x1948020?, 0xc000648050?}, {0x0, ...})
      	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.82.1-0.20240513144526-3242c866b548/pkg/tfshim/sdk-v2/provider2.go:134 +0xa5
      github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.(*providerWithPlanResourceChangeDispatch).Diff(0xc00061c840, {0x195b7e8, 0xc000297e00}, {0x16df8d6, 0xe}, {0x0, 0x0}, {0x1948020, 0xc000648050}, {0x0, ...})
      	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.82.1-0.20240513144526-3242c866b548/pkg/tfshim/sdk-v2/provider2.go:688 +0xe5
      github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Create(0xc0003ef300, {0x195b7e8?, 0xc0002979e0?}, 0xc0006180f0)
      	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.82.1-0.20240513144526-3242c866b548/pkg/tfbridge/provider.go:1096 +0x74e
      github.com/pulumi/pulumi-docker/provider/v4.dockerHybridProvider.Create({{}, {0x24cd200, 0x2992b, 0x2992b}, {0x1945050, 0x1e}, {0x196e220, 0xc0003ef300}, {0x196e0b0, 0xc0003b1090}}, ...)
      	/home/runner/work/pulumi-docker/pulumi-docker/provider/hybrid.go:130 +0xa3
      github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler.func1({0x195b7e8, 0xc0002979e0}, {0x15d08e0?, 0xc0006180f0})
      	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.115.2/proto/go/provider_grpc.pb.go:593 +0x72
      github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x195b7e8, 0xc000297620}, {0x15d08e0, 0xc0006180f0}, 0xc000112080, 0xc0005ee[408](https://github.com/pulumi/pulumi-docker/actions/runs/9065201571/job/24905969782?pr=1095#step:27:420))
      	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3d0
      github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler({0x165e7c0?, 0xc0006763c0}, {0x195b7e8, 0xc000297620}, 0xc0002ea800, 0xc0005e4740)
      	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.115.2/proto/go/provider_grpc.pb.go:595 +0x135
      google.golang.org/grpc.(*Server).processUnaryRPC(0xc000334600, {0x195b7e8, 0xc000297590}, {0x1969a60, 0xc0002a0c00}, 0xc000378000, 0xc000723920, 0x2515060, 0x0)
      	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1369 +0xe23
      google.golang.org/grpc.(*Server).handleStream(0xc000334600, {0x1969a60, 0xc0002a0c00}, 0xc000378000)
      	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1780 +0x1016
      google.golang.org/grpc.(*Server).serveStreams.func2.1()
      	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
      created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 14
      	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1030 +0x135
  
      warning: using pulumi-resource-docker from $PATH at /home/runner/work/pulumi-docker/pulumi-docker/bin/pulumi-resource-docker
      warning: using pulumi-resource-docker from $PATH at /home/runner/work/pulumi-docker/pulumi-docker/bin/pulumi-resource-docker
      error: update failed
  
      warning: using pulumi-resource-docker from $PATH at /home/runner/work/pulumi-docker/pulumi-docker/bin/pulumi-resource-docker
      warning: using pulumi-resource-docker from $PATH at /home/runner/work/pulumi-docker/pulumi-docker/bin/pulumi-resource-docker
  
  Resources:
      + 1 created
  
  Duration: 1s
```

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment]
I suspect these might all be https://github.com/pulumi/pulumi-terraform-bridge/issues/1916 and https://github.com/pulumi/pulumi-terraform-bridge/issues/1915

**Comment by VenelinMartinov** [comment]
@t0yv0 pointed out they are all in state upgrades

**Comment by VenelinMartinov** [comment]
I'll close this as a dupe of https://github.com/pulumi/pulumi-terraform-bridge/issues/2034 as that one has a bit more context
