### ISSUE TITLE
Panic when working with `types.Dynamic`

### ISSUE THREAD

**Issue by dirien** [pulumi/pulumi-terraform-bridge#1988]
### What happened?

The newest version of the azapi provider introduced this TF datatype called:

```yaml
Body                  types.Dynamic  `tfsdk:"body"`
```

This leads during the bridging to this error panic:

```bash
panic: fatal: A failure has occurred: impossible: sch.Type() should be one of TypeMap, TypeList, TypeSet at this point path: resource[key="azapi_data_plane_resource",token="azapi:index/dataPlaneResource:DataPlaneResource"].outputs.body, type: 

goroutine 1 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /Users/dirien/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.114.0/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Failf({0x101c39532?, 0x6e?}, {0x14000c4f008?, 0x14000693b84?, 0x9d?})
        /Users/dirien/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.114.0/go/common/util/contract/fail.go:32 +0xbc
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).makePropertyType(0x1400074a008, {0x10f9cb9c8, 0x140007c3f50}, {0x101b4d79d, 0x4}, {0x10f9effe0, 0x14000834480}, 0x0, 0x1, {{0x14000ac2000, ...}, ...})
        /Users/dirien/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.82.0/pkg/tfgen/generate.go:427 +0x4b8
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).propertyVariable(0x1400074a008, {0x10f9cb908, 0x140008e9db0}, {0x101b4d79d, 0x4}, {0x10f9ddf50, 0x140008e9dc0}, 0x14000bb0000, {0x140009bab60, 0x61}, ...)
        /Users/dirien/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.82.0/pkg/tfgen/generate.go:1687 +0x290
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).gatherResource(0x1400074a008, {0x140001ce800, 0x19}, {0x10f9de8b0, 0x140008e94d0}, 0x140001fcc00, 0x0)
        /Users/dirien/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.82.0/pkg/tfgen/generate.go:1272 +0x568
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).gatherResources(0x1400074a008)
        /Users/dirien/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.82.0/pkg/tfgen/generate.go:1174 +0x274
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).gatherPackage(0x1400074a008)
        /Users/dirien/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.82.0/pkg/tfgen/generate.go:1032 +0x1cc
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).Generate(0x1400074a008)
        /Users/dirien/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.82.0/pkg/tfgen/generate.go:890 +0x54
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.Main.func1({{0x101b4e105, 0x5}, {0x10f3d6cc0, 0x26}, {0x16f7f746e, 0x6}, {{0x10f9edb10, 0x14000870da0}, {0x101b4e105, 0x5}, ...}, ...})
        /Users/dirien/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.82.0/pkg/tfgen/main.go:51 +0x50
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.newTFGenCmd.func1(0x0?, {0x140002aefc0, 0x1, 0x0?})
        /Users/dirien/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.82.0/pkg/tfgen/main.go:167 +0x450
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.newTFGenCmd.RunFunc.func4(0x0?, {0x140002aefc0?, 0x0?, 0x0?})
        /Users/dirien/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.114.0/go/common/util/cmdutil/exit.go:99 +0x28
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.newTFGenCmd.RunFunc.RunResultFunc.func6(0x140001b3508, {0x140002aefc0, 0x1, 0x4})
        /Users/dirien/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.114.0/go/common/util/cmdutil/exit.go:115 +0x34
github.com/spf13/cobra.(*Command).execute(0x140001b3508, {0x140001dc010, 0x4, 0x4})
        /Users/dirien/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0x828
github.com/spf13/cobra.(*Command).ExecuteC(0x140001b3508)
        /Users/dirien/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/dirien/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.MainWithCustomGenerate({_, _}, {_, _}, {{0x10f9edb10, 0x14000870da0}, {0x101b4e105, 0x5}, {0x0, 0x0}, ...}, ...)
        /Users/dirien/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.82.0/pkg/tfgen/main.go:64 +0x54
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.Main({_, _}, {_, _}, {{0x10f9edb10, 0x14000870da0}, {0x101b4e105, 0x5}, {0x0, 0x0}, ...})
        /Users/dirien/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.82.0/pkg/tfgen/main.go:43 +0xe0
main.main()
        /Users/dirien/Tools/repos/pulumi-azapi/provider/cmd/pulumi-tfgen-azapi/main.go:24 +0x8c
make: *** [tfgen] Error 2
```

### Example

-

### Output of `pulumi about`

-

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
`types.Dynamic` should be translated to `any` in Pulumi's type system. I expect this to be quick to resolve.

**Comment by mikhailshilkov** [comment]
@dirien Do you still experience the issue and do you still have an example handy?

**Comment by dirien** [comment]
@mikhailshilkov yes still and will do create the example, had no time (PTO 🙈)

**Comment by dirien** [comment]
Example is in this branch:

https://github.com/dirien/pulumi-azapi/tree/upgrade-terraform-provider-azapi-to-v1.13.1

**Comment by guineveresaenger** [comment]
Thanks for providing us with an example, @dirien. We'll address the panic and add this work to our planning process.
