### ISSUE TITLE
tfgen fails if source provider repository contains incorrectly formatted docs

### ISSUE THREAD

**Issue by terryyanko** [pulumi/pulumi-terraform-bridge#2176]
### What happened?

tfgen fails with a vague index out of range error when it encounters a source repository that contains docs not properly formatted according to Hashicorp specifications. 

The error handling should be improved to account for the possibility that the source doc formatting doesn't match the [specified regex](https://github.com/pulumi/pulumi-terraform-bridge/blob/fa03b81ef0400d397dcedec939a0961ebb46711f/pkg/tfgen/docs.go#L529)  or [contain at least one section header](https://github.com/pulumi/pulumi-terraform-bridge/blob/fa03b81ef0400d397dcedec939a0961ebb46711f/pkg/tfgen/docs.go#L533) and throw a warning accordingly. Additionally, panic may be overkill for this scenario, I suggest simply logging the warning and proceeding with the terraform compilation. 

See [Slack thread](https://pulumi-community.slack.com/archives/C04NPQTRKM4/p1720713054437709) for further details.

### Example

Set the source provider repository in `provider/go.mod` to a repo that contains docs NOT formatted to Hashicorp specifications as outlined in [here](https://developer.hashicorp.com/terraform/registry/providers/docs). For example, https://github.com/nats-io/terraform-provider-jetstream.

Run `go mod tidy` from `/providers` followed by `make tfgen` to produce the following error:
```
➜  pulumi-jetstream git:(main) make tfgen   
[ -x /opt/homebrew/bin/pulumi ] || curl -fsSL https://get.pulumi.com/ | sh
pulumi plugin install resource random 4.3.1
cd provider && go build -o /Users/terryyanko/triplewhale/pulumi-jetstream/bin/pulumi-tfgen-jetstream -ldflags "-X github.com/Triple-Whale/pulumi-jetstream/provider/pkg/version.Version=0.0.1-alpha.1720709561+f0ffa6ba" github.com/Triple-Whale/pulumi-jetstream/provider/cmd/pulumi-tfgen-jetstream
/Users/terryyanko/triplewhale/pulumi-jetstream/bin/pulumi-tfgen-jetstream schema --out provider/cmd/pulumi-resource-jetstream
warning: Found <elided> in description for [jetstream_consumer], but was able to preserve the examples. The description proper will be dropped in the Pulumi provider.
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.reformatExamples({0x14000999260, 0x2, 0x2})
        /Users/terryyanko/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.80.0/pkg/tfgen/docs.go:619 +0xc18
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*tfMarkdownParser).parse(0x14000776638, {0x140009a0000, 0x283, 0x284})
        /Users/terryyanko/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.80.0/pkg/tfgen/docs.go:580 +0x1e0
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.parseTFMarkdown(0x0?, {0x102703668?, 0x140001cefc0?}, {0x10194ef24?, 0x10?}, {0x140009a0000?, 0x14000776998?, 0x100394fbc?}, {0x14000d0bef0?, 0x104054108?}, ...)
        /Users/terryyanko/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.80.0/pkg/tfgen/docs.go:493 +0xfc
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.getDocsForResource(0x140007b6388, {0x1026f3ce0, 0x140002ff340}, {0x10194ef24, 0x9}, {0x101962a37, 0x12}, {0x102703668, 0x140001cefc0})
        /Users/terryyanko/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.80.0/pkg/tfgen/docs.go:314 +0x18c
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).gatherResource(0x140007b6388, {0x101962a37, 0x12}, {0x10270ef60, 0x14000c07a40}, 0x140001cefc0, 0x0)
        /Users/terryyanko/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.80.0/pkg/tfgen/generate.go:1210 +0x374
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).gatherResources(0x140007b6388)
        /Users/terryyanko/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.80.0/pkg/tfgen/generate.go:1154 +0x274
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).gatherPackage(0x140007b6388)
        /Users/terryyanko/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.80.0/pkg/tfgen/generate.go:1012 +0x1cc
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).Generate(0x140007b6388)
        /Users/terryyanko/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.80.0/pkg/tfgen/generate.go:870 +0x54
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.Main.func1({{0x10194eeb8, 0x9}, {0x102106500, 0x1f}, {0x16fa832a2, 0x6}, {{0x10271dfe0, 0x14000a98600}, {0x10194eeb8, 0x9}, ...}, ...})
        /Users/terryyanko/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.80.0/pkg/tfgen/main.go:48 +0x50
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.newTFGenCmd.func1(0x0?, {0x14000736a20, 0x1, 0x0?})
        /Users/terryyanko/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.80.0/pkg/tfgen/main.go:164 +0x450
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.newTFGenCmd.RunFunc.func4(0x0?, {0x14000736a20?, 0x0?, 0x0?})
        /Users/terryyanko/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.113.0/go/common/util/cmdutil/exit.go:99 +0x28
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.newTFGenCmd.RunFunc.RunResultFunc.func6(0x1400097a608, {0x14000736a20, 0x1, 0x3})
        /Users/terryyanko/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.113.0/go/common/util/cmdutil/exit.go:115 +0x34
github.com/spf13/cobra.(*Command).execute(0x1400097a608, {0x140001dc010, 0x3, 0x3})
        /Users/terryyanko/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0x828
github.com/spf13/cobra.(*Command).ExecuteC(0x1400097a608)
        /Users/terryyanko/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/terryyanko/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.MainWithCustomGenerate({_, _}, {_, _}, {{0x10271dfe0, 0x14000a98600}, {0x10194eeb8, 0x9}, {0x0, 0x0}, ...}, ...)
        /Users/terryyanko/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.80.0/pkg/tfgen/main.go:61 +0x54
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.Main({_, _}, {_, _}, {{0x10271dfe0, 0x14000a98600}, {0x10194eeb8, 0x9}, {0x0, 0x0}, ...})
        /Users/terryyanko/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.80.0/pkg/tfgen/main.go:40 +0x64
main.main()
        /Users/terryyanko/triplewhale/pulumi-jetstream/provider/cmd/pulumi-tfgen-jetstream/main.go:25 +0x8c
make: *** [tfgen] Error 2
```

### Output of `pulumi about`

CLI          
Version      3.122.0
Go Version   go1.22.4
Go Compiler  gc

Host     
OS       darwin
Version  14.4.1
Arch     arm64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com
User           Unknown
Organizations  
Token type     personal

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment]
Hey @terryyanko, thanks for reporting the issue and sorry you hit this!

You are correct the panic here is certainly not what we'd like users to see - the bridge should indeed fail the example and go on with the conversion process.

As a workaround you can skip a specific resource's docs by specifying the following in its resource info bit:
```golang
"resource_name": {
		Docs: &tfbridge.DocInfo{
			Markdown: []byte(" "),
		},
	},
```

**Comment by terryyanko** [comment]
Thanks @VenelinMartinov for handling this so quickly and providing the workaround!
