### ISSUE TITLE
runtime error during upgrade-provider

### ISSUE THREAD

**Issue by dirien** [pulumi/pulumi-terraform-bridge#2453]
### What happened?

During the the run of upgrade-provider in the tfgen step, I got following error message during the generation of the examples:

```bash
warning: Found <elided> in description for [scaleway_account_project]. The description and any examples will be dropped in the Pulumi provider.
warning: could not find docs for resource 'scaleway_apple_silicon_server'. Override the Docs property in the resource mapping. See type tfbridge.DocInfo for details.
warning: Found <elided> in description for [scaleway_cockpit]. The description and any examples will be dropped in the Pulumi provider.
warning: parseImports "scaleway:index/domainZone:DomainZone" should not render <elided> text in its emitted markdown.
**Input**:\n
This section explains how to import a zone using the `{subdomain}.{domain}` format.
bash
terraform import scaleway_domain_zone.test test.scaleway-terraform.com

\n\n**Rendered**:
## Import
This section explains how to import a zone using the `{subdomain}.{domain}` format.
bash
sh
$ pulumi import scaleway:index/domainZone:DomainZone test test.scaleway-terraform.com

warning: Found <elided> in description for [scaleway_domain_zone]. The description and any examples will be dropped in the Pulumi provider.
warning: Found <elided> in docs for argument [deploy] in [scaleway_function]. The argument's description will be dropped in the Pulumi provider.
warning: Found <elided> in docs for argument [zip_hash] in [scaleway_function]. The argument's description will be dropped in the Pulumi provider.
warning: Found <elided> in description for [scaleway_function]. The description and any examples will be dropped in the Pulumi provider.
warning: Found <elided> in docs for nested argument [inbound_rule.port_range] in [scaleway_instance_security_group]. The argument's description will be dropped in the Pulumi provider.
warning: Found <elided> in description for [scaleway_instance_security_group]. The description and any examples will be dropped in the Pulumi provider.
warning: Found <elided> in docs for nested argument [inbound_rule.port_range] in [scaleway_instance_security_group_rules]. The argument's description will be dropped in the Pulumi provider.
warning: Found <elided> in description for [scaleway_iot_device], but was able to preserve the examples. The description proper will be dropped in the Pulumi provider.
warning: Found <elided> in description for [scaleway_iot_hub], but was able to preserve the examples. The description proper will be dropped in the Pulumi provider.
warning: Found <elided> in description for [scaleway_iot_network], but was able to preserve the examples. The description proper will be dropped in the Pulumi provider.
warning: Found <elided> in description for [scaleway_iot_route], but was able to preserve the examples. The description proper will be dropped in the Pulumi provider.
warning: Found <elided> in docs for argument [address] in [scaleway_ipam_ip]. The argument's description will be dropped in the Pulumi provider.
warning: Found <elided> in docs for attribute [current_size] in [scaleway_k8s_pool]. The attribute's description will be dropped in the Pulumi provider.
warning: Found <elided> in description for [scaleway_k8s_pool]. The description and any examples will be dropped in the Pulumi provider.
warning: Found <elided> in description for [scaleway_lb_certificate]. The description and any examples will be dropped in the Pulumi provider.
warning: Found <elided> in docs for argument [project_id] in [scaleway_object]. The argument's description will be dropped in the Pulumi provider.
warning: Found <elided> in docs for argument [bucket] in [scaleway_object]. The argument's description will be dropped in the Pulumi provider.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c74f71]
goroutine 1 [running]:
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.parseArgReferenceSection.func2({0xc000e1c44f, 0x0})
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.91.1/pkg/tfgen/docs.go:1078 +0x171
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.parseArgReferenceSection({0xc000822008?, 0xc000b59c08?, 0x3a?}, 0xc00150cc78)
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.91.1/pkg/tfgen/docs.go:1130 +0x3d1
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*tfMarkdownParser).parseSection(0xc00150c9c8, {0xc000b59[808](https://github.com/dirien/pulumi-scaleway/actions/runs/11084918514/job/30800746621#step:2:829), 0x3b, 0x3b})
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.91.1/pkg/tfgen/docs.go:757 +0xa1e
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*tfMarkdownParser).parse(0xc00150c9c8, {0xc00001cf00, 0x2139, 0x213a})
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.91.1/pkg/tfgen/docs.go:578 +0x3b1
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.parseTFMarkdown(0x0?, {0x3076ce8?, 0xc000000540?}, {0x27f8403?, 0x0?}, {0xc00001cf00?, 0x0?, 0x0?}, {0xc00133fd40, 0x10}, ...)
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.91.1/pkg/tfgen/docs.go:474 +0x196
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.getDocsForResource(0xc000f59508, {0x3070f50, 0xc0006f4000}, {0x27f8403, 0x9}, {0x281a8ce, 0x16}, {0x3076ce8, 0xc000000540})
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.91.1/pkg/tfgen/docs.go:237 +0x28d
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).gatherResource(0xc000f59508, {0x281a8ce, 0x16}, {0x3083e40, 0xc0009766e0}, 0xc000000540, 0x0)
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.91.1/pkg/tfgen/generate.go:1313 +0x213
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).gatherResources(0xc000f59508)
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.91.1/pkg/tfgen/generate.go:1254 +0x2c8
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).gatherPackage(0xc000f59508)
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.91.1/pkg/tfgen/generate.go:1105 +0x229
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).generateSchemaResult(0xc000f59508, {0x3076af0?, 0x4589f40?})
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.91.1/pkg/tfgen/generate.go:950 +0x5b
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).Generate(0xc000f59508)
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.91.1/pkg/tfgen/generate.go:934 +0x26
github.com/pulumi/pulumi-terraform-bridge/pf/tfgen.MainWithMuxer.func1({{0x27f5dcf, 0x8}, {0x304a390, 0xc}, {0x7ffee2b2ea11, 0x6}, {{0x3097520, 0xc0009b6e80}, {0x27f5dcf, 0x8}, ...}, ...})
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.1/tfgen/main.go:112 +0x22c
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.newTFGenCmd.func1(0x0?, {0xc000e4ede0, 0x1, 0x0?})
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.91.1/pkg/tfgen/main.go:168 +0x5fc
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.newTFGenCmd.RunFunc.func4(0xc000b0[830](https://github.com/dirien/pulumi-scaleway/actions/runs/11084918514/job/30800746621#step:2:851)8, {0xc000e4ede0, 0x1, 0x3})
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.133.0/go/common/util/cmdutil/exit.go:99 +0x3b
github.com/spf13/cobra.(*Command).execute(0xc000b08308, {0xc000052090, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0xc000b08308)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.MainWithCustomGenerate({_, _}, {_, _}, {{0x3097520, 0xc0009b6e80}, {0x27f5dcf, 0x8}, {0x0, 0x0}, ...}, ...)
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.91.1/pkg/tfgen/main.go:65 +0x6f
github.com/pulumi/pulumi-terraform-bridge/pf/tfgen.MainWithMuxer({_, _}, {{0x3097520, 0xc0009b6e80}, {0x27f5dcf, 0x8}, {0x0, 0x0}, {0x27f5dcf, 0x8}, ...})
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.1/tfgen/main.go:89 +0x26e
main.main()
	/home/runner/work/pulumi-scaleway/pulumi-scaleway/provider/cmd/pulumi-tfgen-scaleway/main.go:24 +0x90
make: *** [Makefile:59: tfgen] Error 2
```

### Example

-

### Output of `pulumi about`

- pulumi-terraform-bridge/v3@v3.91.1
- pulumi-terraform-bridge/pf@v0.44.1
- pulumi/sdk/v3@v3.133.0

### Additional context

Here is the link to the workflow run in GitHub: https://github.com/dirien/pulumi-scaleway/actions/runs/11084918514/job/30800746621

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment]
Thanks for reporting @dirien! We'll investigate the panic. In the meantime you should be able to unblock yourself with by skipping the problematic docs by overwriting them in the provider `resources.go`. The problematic resource is https://www.pulumi.com/registry/packages/scaleway/api-docs/objectbucket/ AFAIK.
