### ISSUE TITLE
panic: index out of range

### ISSUE THREAD

**Issue by tgummerer** [pulumi/pulumi-terraform-bridge#2468]
This panic was found in the cloudflare provider.

```
panic: runtime error: index out of range [0] with length 0 [recovered] 
 panic: runtime error: index out of range [0] with length 0 
goroutine 57 [running]: 
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).recoverOnTypeError(0x1?, {0xc001222280?, 0x0?}, {0x2e25640, 0xc00189cc48}) 
 /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.91.1/pkg/tfbridge/provider.go:250 +0x136 
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.callWithRecover[...].func1() 
 /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.91.1/pkg/tfbridge/provider.go:233 +0x64 
panic({0x2e25640?, 0xc00189cc48?}) 
 /home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.1.linux-amd64/src/runtime/panic.go:785 +0x132 
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.resourceCloudflareZoneSettingsOverrideStateUpgradeV1.func1(...) 
 /home/runner/work/pulumi-cloudflare/pulumi-cloudflare/upstream/internal/sdkv2provider/resource_cloudflare_zone_settings_override_migrate.go:47 
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.resourceCloudflareZoneSettingsOverrideStateUpgradeV1({0x0?, 0x0?}, 0xc001cdced0, {0x0?, 0x0?}) 
 /home/runner/work/pulumi-cloudflare/pulumi-cloudflare/upstream/internal/sdkv2provider/resource_cloudflare_zone_settings_override_migrate.go:53 +0x1c9 
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.UpgradeJSONState({0x36bf088, 0xc001cce7b0}, 0x3150697?, 0xd?, 0x31629ae?, {0x313a3e0, 0xc001f24000}) 
 /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20240520223432-0c0bf0d65f10/helper/schema/grpc_provider.go:495 +0x67 
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).upgradeJSONState(...) 
 /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20240520223432-0c0bf0d65f10/helper/schema/grpc_provider.go:506 
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).UpgradeResourceState(0xc000f2dec0, {0x36bf088?, 0xc001c86e10?}, 0xc00126bec0) 
 /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20240520223432-0c0bf0d65f10/helper/schema/grpc_provider.go:367 +0x408 
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.upgradeResourceStateGRPC({0x36bf088, 0xc001c86e10}, {0x3191a47, 0x21}, 0xc00120fdc0, {{{0x36bf830?, 0xc001d32550?}}, {0x2930fe0?, 0xc001cbd5f0?}}, 0xc001c9a300, ...) 
 /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.91.1/pkg/tfshim/sdk-v2/upgrade_state.go:47 +0x1c8 
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.(*planResourceChangeImpl).upgradeState(0xc000f2ded8, {0x36bf088, 0xc001c86e10}, {0x3191a47, 0x21}, {0x36bf7c0, 0xc001193b40}) 
 /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.91.1/pkg/tfshim/sdk-v2/provider2.go:481 +0x136 
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.(*providerWithPlanResourceChangeDispatch).Diff(0xc00122d3b0, {0x36bf088, 0xc001c86e10}, {0x3191a47, 0x21}, {0x36bf7c0, 0xc001193b40}, {0x369c120, 0xc00110c8c0}, {0x0, ...}) 
 /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.91.1/pkg/tfshim/sdk-v2/provider2.go:827 +0xf0 
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Diff.func1() 
 /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.91.1/pkg/tfbridge/provider.go:1151 +0x78 
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.callWithRecover[...]({0xc001222280?, 0xc0012a8008?}, 0xc001cbd650?, 0x36c5160?) 
 /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.91.1/pkg/tfbridge/provider.go:238 +0x82 
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Diff(0xc0012a8008, {0x36bf088?, 0xc001c869f0?}, 0xc000d9c960) 
 /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.91.1/pkg/tfbridge/provider.go:1150 +0xa26 
github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).Diff.func1({0x36e5040?, 0xc0012a8008?}) 
 /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.9-0.20240403143912-aaea88a50769/muxer.go:369 +0x30 
github.com/pulumi/pulumi-terraform-bridge/x/muxer.resourceMethod[...](0xc000166ba0?, 0x2f44860, 0xc000d556b8?) 
 /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.9-0.20240403143912-aaea88a50769/muxer.go:334 +0xb5 
github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).Diff(0x5231cd0?, {0x36bf088?, 0xc001c869f0?}, 0x271f520?) 
 /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.9-0.20240403143912-aaea88a50769/muxer.go:368 +0x4a 
github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Diff_Handler.func1({0x36bf088?, 0xc001c869f0?}, {0x2f69720?, 0xc000d9c960?}) 
 /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.133.0/proto/go/provider_grpc.pb.go:633 +0xcb 
github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x36bf088, 0xc001c86630}, {0x2f69720, 0xc000d9c960}, 0xc0016ae140, 0xc0016a4198) 
 /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3c4 
github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Diff_Handler({0x30aef40, 0xc000166ba0}, {0x36bf088, 0xc001c86630}, 0xc001342300, 0xc001b0d700) 
 /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.133.0/proto/go/provider_grpc.pb.go:635 +0x143 
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000f95000, {0x36bf088, 0xc001c865a0}, {0x36d4900, 0xc00201bba0}, 0xc000b0c7e0, 0xc000f79a70, 0x5279240, 0x0) 
 /home/runner/go/pkg/mod/google.golang.org/grpc@v1.66.2/server.go:1394 +0xe2b 
google.golang.org/grpc.(*Server).handleStream(0xc000f95000, {0x36d4900, 0xc00201bba0}, 0xc000b0c7e0) 
 /home/runner/go/pkg/mod/google.golang.org/grpc@v1.66.2/server.go:1805 +0xe8b 
google.golang.org/grpc.(*Server).serveStreams.func2.1() 
 /home/runner/go/pkg/mod/google.golang.org/grpc@v1.66.2/server.go:1029 +0x7f 
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 55 
 /home/runner/go/pkg/mod/google.golang.org/grpc@v1.66.2/server.go:1040 +0x125 
error reading from server: EOF 
```

[metabase link](https://metabase.corp.pulumi.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjo0LCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjE2NTYsIm9yZGVyLWJ5IjpbWyJhc2MiLFsiZmllbGQiLDM3NzY4LHsiYmFzZS10eXBlIjoidHlwZS9OdW1iZXIifV1dXSwiZmllbGRzIjpbWyJmaWVsZCIsMzc3NjQseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV1dLCJmaWx0ZXIiOlsiPSIsWyJmaWVsZCIsMzc3NjEseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sImRlZjA1YWQ2MmJmNjhhNTRlYWNlYmQyN2UyMTU2NDBiMDIyYzJhZDQ2Yzk3Y2FiMGE4NWEwOWRlIl19fSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e30sInR5cGUiOiJxdWVzdGlvbiJ9)

**Comment by sebabarre-evaneos** [comment]
Hello, is anyone is investigated this ? I have the same issue on one of our stack.

**Comment by t0yv0** [comment]
We would appreciate a repro to investigate specific issues per provider.

It would appear that https://github.com/pulumi/pulumi-terraform-bridge/issues/1667 is related. There are some discrepancies in the data that gets sent into state upgraders under the bridge vs TF proper.

**Comment by VenelinMartinov** [comment]
Cloudflare had a major version release which replaced this code, so this issue is no longer relevant
