### ISSUE TITLE
[panic] Set not supported - is it possible to treat this as immutable?

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi-terraform-bridge#2585]
### What happened?

After preparing auto-mapping to my provider codebase, I wanted to remove the manual mappings. On one specific datasource, I got this panic:

```sh
$ make provider build_sdks
pulumi/bin/pulumi version: v3.137.0
.pulumi/bin/pulumi plugin install converter terraform 1.0.19
(cd provider && go build  -o /Users/ringods/Projects/pulumiverse/pulumi-cockroach/bin/pulumi-tfgen-cockroach -ldflags "-X github.com/pulumiverse/pulumi-cockroach/provider/pkg/version.Version=0.0.0-alpha.0+dev " github.com/pulumiverse/pulumi-cockroach/provider/cmd/pulumi-tfgen-cockroach)
/Users/ringods/Projects/pulumiverse/pulumi-cockroach/bin/pulumi-tfgen-cockroach schema --out provider/cmd/pulumi-resource-cockroach
panic: Set not supported - is it possible to treat this as immutable?

goroutine 1 [running]:
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/pf/internal/schemashim.(*schemaOnlyDataSourceMap).Set(0x10240ac60?, {0x1400005af90?, 0x1400005b5f0?}, {0x18?, 0x2?})
        /Users/ringods/Projects/golang/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.94.0/pkg/pf/internal/schemashim/datasource_map.go:54 +0x2c
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge/info.(*Provider).RenameDataSource(0x14000813448, {0x1400005af90, 0x11}, {0x103609447, 0x37}, {0x1400081fa10, 0x25}, {0x103609451, 0x19}, {0x1400081fa1a, ...}, ...)
        /Users/ringods/Projects/golang/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.94.0/pkg/tfbridge/info/rename.go:87 +0x404
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.autoDataSourceSettings.apply({{0x14000a5bb90, 0x1, 0x1}, 0x0}, 0x14000813448, {0x1400005af90, 0x11})
        /Users/ringods/Projects/golang/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.94.0/pkg/tfbridge/auto_aliasing.go:603 +0x138
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*autoSettings).apply(0x1400039f660, 0x14000813448)
        /Users/ringods/Projects/golang/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.94.0/pkg/tfbridge/auto_aliasing.go:565 +0x120
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.ApplyAutoAliases(0x14000813448)
        /Users/ringods/Projects/golang/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.94.0/pkg/tfbridge/auto_aliasing.go:91 +0x2b0
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge/info.(*Provider).MustApplyAutoAliases(0x14000813448?)
        /Users/ringods/Projects/golang/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.94.0/pkg/tfbridge/info/external_methods.go:39 +0x1c
github.com/pulumiverse/pulumi-cockroach/provider.Provider()
        /Users/ringods/Projects/pulumiverse/pulumi-cockroach/provider/resources.go:236 +0x265c
main.main()
        /Users/ringods/Projects/pulumiverse/pulumi-cockroach/provider/cmd/pulumi-tfgen-cockroach/main.go:10 +0x24
make: *** [tfgen_no_deps] Error 2
```

### Example

* Clone https://github.com/pulumiverse/pulumi-cockroach
* current latest on `main` should be [2879aae](https://github.com/pulumiverse/pulumi-cockroach/commit/2879aae3f4c91a7a294f5e5535a266417aad14c3)
* remove the `cockroach_cluster` datasource on [line 188](https://github.com/pulumiverse/pulumi-cockroach/blob/2879aae3f4c91a7a294f5e5535a266417aad14c3/provider/resources.go#L188). Only this datasource generates the panic.
* run `make provider build_sdks` and (hopefully) see it panic when running tfgen.

### Output of `pulumi about`

```
CLI          
Version      3.137.0
Go Version   go1.23.2
Go Compiler  gc

Host     
OS       darwin
Version  15.1
Arch     arm64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
We need to take the https://github.com/pulumi/pulumi-terraform-bridge/pull/1938 fix and make it also apply to data sources.

[#1938 Fix automatic aliasing of muxed providers](https://github.com/pulumi/pulumi-terraform-bridge/pull/1938)

**Comment by ringods** [comment]
@VenelinMartinov provider upgrade ran succesful with the new release:

https://github.com/pulumiverse/pulumi-cockroach/pull/54
