### ISSUE TITLE
aws.budget.Budget: Unexpected type 'list' during pulumi preview

### ISSUE THREAD

**Issue by cheapRoc** [pulumi/pulumi-terraform-bridge#286]
The following Python program results in an error during preview:

```
$ pulumi version
v2.11.2
```

```
$ venv/bin/python -m pip list
Package      Version
------------ ---------
Arpeggio     1.9.2
attrs        19.3.0
certifi      2020.6.20
cffi         1.14.3
chardet      3.0.4
cryptography 3.1.1
dill         0.3.2
grpcio       1.31.0
idna         2.10
parver       0.3.0
pip          20.2.3
protobuf     3.13.0
pulumi       2.9.0
pulumi-aws   3.5.0
pulumi-gcp   3.19.0
pycparser    2.20
pyOpenSSL    19.1.0
requests     2.24.0
semver       2.10.2
setuptools   47.1.0
six          1.15.0
urllib3      1.25.10
```

```
budget = budgets.Budget("test-ec2-budget",
                        budget_type="COST",
                        limit_amount="1200",
                        limit_unit="USD",
                        notifications=[budgets.BudgetNotificationArgs(
                            comparison_operator="EQUAL_TO",
                            notification_type="ACTUAL",
                            subscriber_email_addresses=["nobody@nowhere.com"],
                            threshold=100,
                            threshold_type="PERCENTAGE"
                        )],
                        time_period_start="2017-07-01_00:00",
                        time_unit="MONTHLY", __opts__=opts)
``` 

```
Diagnostics:
  pulumi:pulumi:Stack (pulumi-budget-alerts-dev):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
        return future.result()
      File "/Users/nobody/dev/cloud/pulumi-budget-alerts/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 83, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/nobody/dev/cloud/pulumi-budget-alerts/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await RPC_MANAGER.rpcs.pop()
      File "/Users/nobody/dev/cloud/pulumi-budget-alerts/venv/lib/python3.8/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc
      File "/Users/nobody/dev/cloud/pulumi-budget-alerts/venv/lib/python3.8/site-packages/pulumi/runtime/resource.py", line 426, in do_register
        await rpc.resolve_outputs(res, resolver.serialized_props, resp.object, resolvers)
      File "/Users/nobody/dev/cloud/pulumi-budget-alerts/venv/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 487, in resolve_outputs
        translated_value = translate_output_properties(value, res.translate_output_property, types.get(key))
      File "/Users/nobody/dev/cloud/pulumi-budget-alerts/venv/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 451, in translate_output_properties
        raise AssertionError(f"Unexpected type. Expected 'list' got '{typ}'")
    AssertionError: Unexpected type. Expected 'list' got 'typing.Sequence[pulumi_aws.budgets.outputs.BudgetNotification]'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

Also, I can create a similar error adding `cost_filters` (and commenting out `notifications`) which is a `Mapping[str, str]` in the Pulumi resource schema.

```
pulumi:pulumi:Stack (pulumi-budget-alerts-dev):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
        return future.result()
      File "/Users/nobody/dev/cloud/pulumi-budget-alerts/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 83, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/nobody/dev/cloud/pulumi-budget-alerts/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await RPC_MANAGER.rpcs.pop()
      File "/Users/nobody/dev/cloud/pulumi-budget-alerts/venv/lib/python3.8/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc
      File "/Users/nobody/dev/cloud/pulumi-budget-alerts/venv/lib/python3.8/site-packages/pulumi/runtime/resource.py", line 426, in do_register
        await rpc.resolve_outputs(res, resolver.serialized_props, resp.object, resolvers)
      File "/Users/nobody/dev/cloud/pulumi-budget-alerts/venv/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 487, in resolve_outputs
        translated_value = translate_output_properties(value, res.translate_output_property, types.get(key))
      File "/Users/nobody/dev/cloud/pulumi-budget-alerts/venv/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 434, in translate_output_properties
        return {
      File "/Users/nobody/dev/cloud/pulumi-budget-alerts/venv/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 436, in <dictcomp>
        translate_output_properties(v, output_transformer, get_type(k))
      File "/Users/nobody/dev/cloud/pulumi-budget-alerts/venv/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 451, in translate_output_properties
        raise AssertionError(f"Unexpected type. Expected 'list' got '{typ}'")
    AssertionError: Unexpected type. Expected 'list' got '<class 'str'>'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

This sounds like #251 so I created the ticket here instead of pulumi-aws. Please let me know if I should move the issue. Thanks.

**Comment by ns-jreagor** [comment]
You can close this. I have a temporary work around which I pulled from other linked tickets. I'm able to perform things by downgrading to...

```
$ cat requirements.txt
pulumi-aws<=2.13.1
pulumi-gcp>=3.0.0,<4.0.0
pulumi<=2.8.2
requests>=2.24.0
```

Looking forward to 251 getting fixed.
