### ISSUE TITLE
InvalidOperationException with custom generated .NET SDK

### ISSUE THREAD

**Issue by Jonne** [pulumi/pulumi-terraform-bridge#314]
Hi!

I'm trying to use the terraform bridge to create a provider for the commerce tools terraform provider: https://github.com/labd/terraform-provider-commercetools

I've been able to successfully generate the SDKS, but when I try to use the .NET SDK i get the following error with some of the resources:

```
    System.InvalidOperationException: Expected System.Collections.Immutable.ImmutableDictionary`2[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] but got System.Collections.Immutable.ImmutableArray`1[[System.Object, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] deserializing Pulumi.Commercetools.Subscription.destination
       at Pulumi.Serialization.Converter.ConvertObject(String context, Object val, Type targetType)
       at Pulumi.Serialization.Converter.ConvertValue(String context, Value value, Type targetType, ImmutableHashSet`1 resources)
       at Pulumi.Deployment.CompleteResourceAsync(Resource resource, Boolean remote, Func`2 newDependency, ResourceArgs args, ResourceOptions options, ImmutableDictionary`2 completionSources)
       at Pulumi.Deployment.Runner.<>c__DisplayClass9_0.<<WhileRunningAsync>g__HandleCompletion|0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at Pulumi.Deployment.Runner.WhileRunningAsync()
```

The repository of the pulumi resource provider can be found here: https://github.com/unplatform-io/pulumi-commercetools

Any idea what this can be?

**Comment by Jonne** [comment]
Hi, anyone had a chace to look at this yet? Or is there a better channel to ask these kind of questions?

**Comment by Jonne** [comment]
Sorry, accidentally closed the issue

**Comment by mikhailshilkov** [comment]
Hey @Jonne 

Could you run an update in debug mode and share the logs?

`TF_LOG=1 pulumi up -v=9 --logtostderr --logflow`

You could email them to mikhail@pulumi.com via a DM in slack

**Comment by mikhailshilkov** [comment]
I think this is the relevant line from the logs (obfuscated):

```
Terraform output destination = {[{map[__defaults:{[]} connectionString:{Endpoint=sb://foo.servicebus.windows.net/;SharedAccessKeyName=test;SharedAccessKey=bar;EntityPath=test} region:{} type:{azure_servicebus} uri:{}]}]}
```

So it looks like an array indeed, while the SDK expects a dictionary. Not sure about what goes wrong where, at this point.

**Comment by Jonne** [comment]
Hi @mikhailshilkov,

Is there anything else I can do to assist?

**Comment by mikhailshilkov** [comment]
Honestly, I don't have a lot of context for this. @stack72 is this on your radar?

**Comment by Jonne** [comment]
@mikhailshilkov @stack72 Any way to move this forward? Or is just not supported to create custom terraform providers? Thanks
