### ISSUE TITLE
Refreshing state on BucketObject causes InvalidOperationException (C#)

### ISSUE THREAD

**Issue by floyd-may** [pulumi/pulumi-terraform-bridge#328]
After refreshing state on a BucketObject, subsequent operations yield an error:

```
System.InvalidOperationException: Expected Pulumi.AssetOrArchive but got System.String deserializing Pulumi.Gcp.Storage.BucketObject.source
       at Pulumi.Serialization.Converter.ConvertObject(String context, Object val, Type targetType)
       at Pulumi.Serialization.Converter.ConvertValue(String context, Value value, Type targetType, ImmutableHashSet`1 resources)
       at Pulumi.Deployment.CompleteResourceAsync(Resource resource, Boolean remote, Func`2 newDependency, ResourceArgs args, ResourceOptions options, ImmutableDictionary`2 completionSources)
       at Pulumi.Deployment.Runner.<>c__DisplayClass9_0.<<WhileRunningAsync>g__HandleCompletion|0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at Pulumi.Deployment.Runner.WhileRunningAsync()
```

## Expected behavior

A refresh doesn't put the stack in an unusable state.

## Current behavior

See above

## Steps to reproduce

1. Create a BucketObject
2. Do `pulumi refresh --yes`
3. Do `pulumi preview`
4. Kaboom

# Additional Information
This seems very similar to what's happening in the Azure provider:
https://github.com/pulumi/pulumi-azure/issues/831

It appears by importing from the checkpoint prior to the `pulumi refresh` I've been able to repair my stack enough to continue forward.

**Comment by floyd-may** [comment]
@pgavlin Thanks for getting on this so quickly, and being so helpful getting this put into the right place 🙏

**Comment by t0yv0** [comment]
This no longer reproduces

```csharp
using System.Collections.Generic;
using System.Linq;
using Pulumi;
using Aws = Pulumi.Aws;

return await Deployment.RunAsync(() =>
{
    var examplekms = new Aws.Kms.Key("examplekms", new()
    {
        Description = "KMS key 1",
        DeletionWindowInDays = 7,
    });

    var examplebucket = new Aws.S3.BucketV2("examplebucket");

    // var exampleBucketAclV2 = new Aws.S3.BucketAclV2("exampleBucketAclV2", new()
    // {
    //     Bucket = examplebucket.Id,
    //     // Acl = "private",
    // });

    var exampleBucketObject = new Aws.S3.BucketObject("exampleBucketObject", new()
    {
        Key = "someobject",
        Bucket = examplebucket.Id,
        Source = new FileAsset("index.html"),
        KmsKeyId = examplekms.Arn,
    });

    // Export the name of the bucket
    return new Dictionary<string, object?>
    {
        ["bucketName"] = exampleBucketObject.Id
    };
});
```

pulumi up
pulumi refresh --yes
pulumi preview # empty preview

```
running 'dotnet build -nologo .'
  Determining projects to restore...

  All projects are up-to-date for restore.

  bridge-328 -> /Users/t0yv0/tmp/2023/08/bridge-328/bin/Debug/net6.0/bridge-328.dll


Build succeeded.

    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.10

'dotnet build -nologo .' completed successfully
CLI          
Version      3.73.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.42.0
dotnet  unknown

Host     
OS       darwin
Version  13.4.1
Arch     x86_64

This project is written in dotnet: executable='/Users/t0yv0/.nix-profile/bin/dotnet' version='6.0.412'

Current Stack: t0yv0/bridge-328/dev

TYPE                              URN
pulumi:pulumi:Stack               urn:pulumi:dev::bridge-328::pulumi:pulumi:Stack::bridge-328-dev
pulumi:providers:aws              urn:pulumi:dev::bridge-328::pulumi:providers:aws::default_5_42_0
aws:s3/bucketV2:BucketV2          urn:pulumi:dev::bridge-328::aws:s3/bucketV2:BucketV2::examplebucket
aws:kms/key:Key                   urn:pulumi:dev::bridge-328::aws:kms/key:Key::examplekms
aws:s3/bucketObject:BucketObject  urn:pulumi:dev::bridge-328::aws:s3/bucketObject:BucketObject::exampleBucketObject


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/t0yv0
User           t0yv0
Organizations  t0yv0, pulumi

Dependencies:
NAME        VERSION
Pulumi      3.55.2
Pulumi.Aws  5.42.0

Pulumi locates its logs in /var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/ by default

```
