### ISSUE TITLE
Strongly typing output property fails to project to a populated object

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-terraform-bridge#35]
Trying to do the following to remap the `root_resource_id` property to a strogly types `Resource`:

```
"aws_api_gateway_rest_api": {
				Tok:    awsrestok(apigatewayMod, "RestApi"),
				Fields: map[string]tfbridge.SchemaInfo{
				 "root_resource_id": {
				 	Name: "rootResource",
				 	Type: awstok(apigatewayMod+"/resource", "Resource"),
				 },
				},
			},
```

leads to `api.rootResource.id` triggering an assert in Pulumi indicating that the resulting object has no `id` member.

```
panic: fatal: An assertion has failed: Missing instance class member 'lumi:resource:Resource:id'

goroutine 9 [running]:
github.com/pulumi/lumi/pkg/util/contract.failfast(0xc42b0bc6c0, 0x52)
	/Users/luke/go/src/github.com/pulumi/lumi/pkg/util/contract/failfast.go:11 +0xf3
github.com/pulumi/lumi/pkg/util/contract.Assertf(0x162e800, 0x1685ca4, 0x22, 0xc42ef3aa60, 0x1, 0x1)
	/Users/luke/go/src/github.com/pulumi/lumi/pkg/util/contract/assert.go:21 +0x178
github.com/pulumi/lumi/pkg/eval.(*evaluator).evalLoadSymbolLocation(0xc42c475260, 0x1939a80, 0xc429e5df20, 0x1945160, 0xc42ba071c0, 0xc427cc5b30, 0x1944980, 0xc429e5dfb0, 0x0, 0xc42ef3aba0, ...)
	/Users/luke/go/src/github.com/pulumi/lumi/pkg/eval/eval.go:1563 +0x967
github.com/pulumi/lumi/pkg/eval.(*evaluator).evalLoadLocation(0xc42c475260, 0xc429e5df20, 0xc429e5d800, 0xc427cad6e0, 0x0)
```

And indeed - `jsonStringify`ing it shows it as `{}` indicating the object has no properties populated.

**Comment by lukehoban** [comment]
We have not re-hit this in the last 2 years, and it isn't a pattern we're really investing in.  We'll reopen if this becomes a practical issue going forward.
