### ISSUE TITLE
Can't create aws.budgets.Budget resource

### ISSUE THREAD

**Issue by agostbiro** [pulumi/pulumi-terraform-bridge#418]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Can't create `aws.budgets.Budget` resource.

### Source

__main__.py
```py
import pulumi
import pulumi_aws as aws

config = pulumi.Config()
monthly_usd_limit = config.require("monthly-usd-limit")
assert isinstance(monthly_usd_limit, str)
email_notifications = config.require_object("email-notifications")
assert isinstance(email_notifications, list)

aws.budgets.Budget(
    "account-budget",
    budget_type="COST",
    limit_amount=monthly_usd_limit,
    limit_unit="USD",
    notifications=[
        aws.budgets.BudgetNotificationArgs(
            comparison_operator="GREATER_THAN",
            notification_type="FORECASTED",
            subscriber_email_addresses=email_notifications,
            threshold=100,
            threshold_type="PERCENTAGE",
        )
    ],
    time_period_end="2087-06-15_00:00",
    time_period_start="2021-01-01_00:00",
    time_unit="MONTHLY",
)
```

Pulumi.yaml
```yaml
name: budget
runtime:
  name: python
  options:
    virtualenv: venv
description: Budget alert
```

Pulumi.default.yaml
```yaml
config:
  aws:region: eu-west-1
  analytics-budget:monthly-usd-limit: 1000
  analytics-budget:email-notifications:
    - "example@example.com"
```

requirements.txt
```
Arpeggio==1.10.2
attrs==21.2.0
dill==0.3.4
grpcio==1.41.1
parver==0.3.1
protobuf==3.19.1
pulumi==3.19.0
pulumi-aws==4.30.0
PyYAML==6.0
semver==2.13.0
six==1.16.0
```

### Steps to reproduce

1. `pulumi stack init --stack default`
2. `pulumi preview --stack default`

Expected: The preview command outputs the resources to be created.
Actual: The preview command fails with the error below.

### Error

```
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/Users/user/homebrew/bin/pulumi-language-python-exec", line 107, in <module>
        loop.run_until_complete(coro)
      File "/Users/user/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
        return future.result()
      File "/Users/user/repos/analytics/budget/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 110, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/user/repos/analytics/budget/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 45, in run_pulumi_func
        await wait_for_rpcs()
      File "/Users/user/repos/analytics/budget/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 94, in wait_for_rpcs
        raise exception
      File "/Users/user/repos/analytics/budget/venv/lib/python3.9/site-packages/pulumi/runtime/rpc_manager.py", line 65, in rpc_wrapper
        result = await rpc
      File "/Users/user/repos/analytics/budget/venv/lib/python3.9/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/Users/user/repos/analytics/budget/venv/lib/python3.9/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/Users/user/repos/analytics/budget/venv/lib/python3.9/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      [Previous line repeated 10 more times]
      File "/Users/user/repos/analytics/budget/venv/lib/python3.9/site-packages/pulumi/runtime/resource.py", line 568, in do_register
        rpc.resolve_outputs(res, resolver.serialized_props, resp.object, deps, resolvers, transform_using_type_metadata)
      File "/Users/user/repos/analytics/budget/venv/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 850, in resolve_outputs
        translated_value = translate_output_properties(value, translate_to_pass, types.get(key),
      File "/Users/user/repos/analytics/budget/venv/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 748, in translate_output_properties
        element_type = _get_list_element_type(typ)
      File "/Users/user/repos/analytics/budget/venv/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 107, in _get_list_element_type
        raise AssertionError(f"Unexpected type. Expected 'list' got '{typ}'")
    AssertionError: Unexpected type. Expected 'list' got 'typing.Mapping[str, str]'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1

```

**Comment by emiliza** [comment]
Able to repro this, and moved this to the appropriate repo. Turns out there was already a related issue for this that didn't actually get resolved https://github.com/pulumi/pulumi-terraform-bridge/issues/286

**Comment by sibuthomasmathew** [comment]
I'm running into the same error too. Strangely, the resource **actually** gets created in the background, in spite of the error. From the output, it appears the error is the result of the stack rather than the `aws:budgets:Budget` resource. Here are the details to reproduce:

### Source

#### __main__.py

```python
import pulumi_aws as aws

alert = aws.budgets.Budget(
    "alert_50",
    budget_type="COST",
    limit_amount="1000",
    limit_unit="USD",
    time_unit="MONTHLY",
)
```

#### requirements.txt

```bash
pulumi> cat requirements.txt 
pulumi>=3.0.0,<4.0.0
pulumi-aws>=4.0.0,<5.0.0
pulumi> 
```

#### pulumi version
```bash
pulumi> pulumi version
v3.24.1
pulumi> 
```
### Output leading to the error

```bash
Updating (dev)


     Type                   Name                         Status                  Info
 +   pulumi:pulumi:Stack    subaccount-budget-alert-dev  **creating failed**     3 errors
 +   └─ aws:budgets:Budget  alert_50                     created                 
 
Diagnostics:
  pulumi:pulumi:Stack (subaccount-budget-alert-dev):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/home/sibu/.pulumi/bin/pulumi-language-python-exec", line 107, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
        return future.result()
      File "/home/sibu/projects/accure/subaccount-budget-alert/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 126, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/home/sibu/projects/accure/subaccount-budget-alert/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await wait_for_rpcs()
      File "/home/sibu/projects/accure/subaccount-budget-alert/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 110, in wait_for_rpcs
        raise exception
      File "/home/sibu/projects/accure/subaccount-budget-alert/venv/lib/python3.8/site-packages/pulumi/runtime/rpc_manager.py", line 68, in rpc_wrapper
        result = await rpc
      File "/home/sibu/projects/accure/subaccount-budget-alert/venv/lib/python3.8/site-packages/pulumi/output.py", line 98, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/home/sibu/projects/accure/subaccount-budget-alert/venv/lib/python3.8/site-packages/pulumi/output.py", line 98, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/home/sibu/projects/accure/subaccount-budget-alert/venv/lib/python3.8/site-packages/pulumi/output.py", line 98, in is_value_known
        return await is_known and not contains_unknowns(await future)
      [Previous line repeated 10 more times]
      File "/home/sibu/projects/accure/subaccount-budget-alert/venv/lib/python3.8/site-packages/pulumi/runtime/resource.py", line 651, in do_register
        rpc.resolve_outputs(
      File "/home/sibu/projects/accure/subaccount-budget-alert/venv/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 981, in resolve_outputs
        translated_value = translate_output_properties(
      File "/home/sibu/projects/accure/subaccount-budget-alert/venv/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 862, in translate_output_properties
        element_type = _get_list_element_type(typ)
      File "/home/sibu/projects/accure/subaccount-budget-alert/venv/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 127, in _get_list_element_type
        raise AssertionError(f"Unexpected type. Expected 'list' got '{typ}'")
    AssertionError: Unexpected type. Expected 'list' got 'typing.Mapping[str, str]'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
 
Resources:
    + 2 created

Duration: 10s
```

**Comment by t0yv0** [comment]
The program listed here work for me on the current latest versions of Pulumi and pulumi-aws:

```
CLI          
Version      3.68.0
Go Version   go1.20.1
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.41.0
python  unknown

Host     
OS       darwin
Version  13.3.1
Arch     x86_64

This project is written in python: executable='/usr/bin/python3' version='3.9.6
'

Current Stack: t0yv0/bridge-418/dev

TYPE                       URN
pulumi:pulumi:Stack        urn:pulumi:dev::bridge-418::pulumi:pulumi:Stack::bridge-418-dev
pulumi:providers:aws       urn:pulumi:dev::bridge-418::pulumi:providers:aws::default_5_41_0
aws:budgets/budget:Budget  urn:pulumi:dev::bridge-418::aws:budgets/budget:Budget::account-budget


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/t0yv0
User           t0yv0
Organizations  t0yv0, pulumi

Dependencies:
NAME        VERSION
pip         23.1.2
pulumi-aws  5.41.0
setuptools  67.8.0
wheel       0.40.0

Pulumi locates its logs in /var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/ by default

```

Please reopen if you can still reproduce. Thank you!
