### ISSUE TITLE
Duplicate underscore panic

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-terraform-bridge#62]
I defined the following (which I'm guessing is wrong in some way, haven't gotten that far):

```typescript
    new aws.lambda.Function("get-handler", {
            runtime: aws.lambda.NodeJS10dXRuntime,
            code: new pulumi.asset.AssetArchive({
                ".": new pulumi.asset.FileArchive("./handler"),
            }),
            handler: "index.handler",
            role: handlerRole.arn,
            environment: hits.name.apply(hn => ({
                "HITS_TABLE": hn,
            })),
        }, { dependsOn: handlerPolicy })
```

Apparently the `"HITS_TABLE"` key is being transformed by our name mangling, leading to:

```
    panic: fatal: An assertion has failed: Unexpected duplicate underscore: h_i_t_s__t_a_b_l_e
    goroutine 118 [running]:
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/pkg/util/contract.failfast(...)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/pkg/util/contract.Assertf(0xc000878500, 0x5eb457a, 0x23, 0xc00099cc38, 0x1, 0x1)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/pkg/util/contract/assert.go:33 +0x198
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge.TerraformToPulumiName(0xc000878560, 0x12, 0x0, 0x0, 0xa8bff20, 0xc00099cca0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge/names.go:74 +0x27d
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge.getInfoFromTerraformName(0xc000878560, 0x12, 0xc000618480, 0x0, 0x203000, 0xc00099cd78, 0x100b759, 0xc000d614f0, 0xc00099cd90)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge/schema.go:953 +0x15d
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge.MakeTerraformOutputs(0xc00099cfd0, 0xc000618480, 0x0, 0xc000dc5b00, 0xc000990100, 0xc000dbc620)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge/schema.go:561 +0x105
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge.MakeTerraformOutput.func1(0x5379c60, 0xc000746000, 0xc000623200, 0x0, 0xc000dc5b00, 0x100, 0x10, 0x4ef73a0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge/schema.go:691 +0xc46
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge.MakeTerraformOutput(0x5379c60, 0xc000746000, 0xc000623200, 0x0, 0xc000dc5b00, 0xc000d60100, 0x0, 0x1)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge/schema.go:699 +0x7d
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge.MakeTerraformOutput.func1(0x4e73860, 0xc000dbc640, 0xc000623200, 0x0, 0xc000dc5b00, 0xc0005e0100, 0xb, 0xb)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge/schema.go:660 +0x3e7
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge.MakeTerraformOutput(0x4e73860, 0xc000dbc640, 0xc000623200, 0x0, 0xc000dc5b00, 0xc000740100, 0xb, 0xc000623200)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge/schema.go:699 +0x7d
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge.MakeTerraformOutputs(0xc000dc5b30, 0xc000618540, 0xc0006e2240, 0xc000dc5b00, 0x100, 0xc000c68058)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge/schema.go:565 +0x177
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge.(*Provider).Check(0xc0005b8000, 0x6836e40, 0xc000dc55f0, 0xc000d70580, 0xc0005b8000, 0x54c3501, 0xc000d70640)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge/provider.go:500 +0x904
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Check_Handler.func1(0x6836e40, 0xc000dc55f0, 0x5c26b80, 0xc000d70580, 0x5cb7060, 0xa8be700, 0x6836e40, 0xc000dc55f0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1520 +0x86
    github.com/pulumi/pulumi-aws/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x6836e40, 0xc000dc4bd0, 0x5c26b80, 0xc000d70580, 0xc000d67380, 0xc000d673a0, 0x0, 0x0, 0x679b680, 0xc0002de010)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x360
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Check_Handler(0x5d3a520, 0xc0005b8000, 0x6836e40, 0xc000dc4bd0, 0xc00090ccc0, 0xc000270020, 0x6836e40, 0xc000dc4bd0, 0xc0007df600, 0x520)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1522 +0x158
    github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005ee000, 0x685c3c0, 0xc000546a80, 0xc000dbe500, 0xc00078a1e0, 0xa890880, 0x0, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:995 +0x466
    github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0005ee000, 0x685c3c0, 0xc000546a80, 0xc000dbe500, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:1275 +0xda6
    github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00016c240, 0xc0005ee000, 0x685c3c0, 0xc000546a80, 0xc000dbe500)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:710 +0x9f
    created by github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:708 +0xa1
```

**Comment by joeduffy** [comment]
Slightly different version also panics:

```
            environment: <aws.types.input.lambda.FunctionEnvironment>{
                "HITS_TABLE": hits.name,
            },
```

**Comment by joeduffy** [comment]
Problem solved. `FunctionEnvironment` isn't actually a map -- it has a `variables` property:

```typescript
            environment: {
                variables: { "HITS_TABLE": hits.name },
            },
```

Seems like not panicking, and emitting an error (e.g. `expected a structure, got a map`), would be nicer.

**Comment by byteSamurai** [comment]
Please add a example to the documentation

**Comment by jkodroff** [comment]
@byteSamurai The registry (at the time of writing this) does include an example which demonstrates the correct usage of `environment` for Lambda functions: https://www.pulumi.com/registry/packages/aws/api-docs/lambda/function/#basic-example

**Comment by woeps** [comment]
Today, I encountered a similar symptom:
```
panic: fatal: An assertion has failed: Unexpected duplicate underscore: b_s__p_r_i_v_a_t_e__n_e_s_t_e_d__s_o_m_e__n_o_n_e
    goroutine 69 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.50.1/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0x40?, {0xd107441?, 0xc002f3c578?}, {0xc002f3c568?, 0xc002f3c5b8?, 0x120?})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.50.1/go/common/util/contract/assert.go:33 +0xed
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.TerraformToPulumiName({0xc001ab0a40, 0x31}, {0x0?, 0x0?}, 0xffffffffffffffff?, 0x0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.36.0/pkg/tfbridge/names.go:106 +0x25f
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.getInfoFromTerraformName({0xc001ab0a40, 0x31}, {0x0, 0x0}, 0xc004fe6630?, 0x0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.36.0/pkg/tfbridge/schema.go:1133 +0x111
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutputs({0xe3ddae8, 0xc0029fc780}, 0x0?, {0x0, 0x0}, 0x98?, 0xc004fe9320?, 0x50?, 0x13?)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.36.0/pkg/tfbridge/schema.go:852 +0x119
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutput.func1({0xe3ddae8, 0xc0029fc780}, {0xb3a2ce0, 0xc004fe9170}, {0xe3e03a0, 0xc000e58b40}, 0x0, 0xc004fe90e0, 0x0, 0x1)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.36.0/pkg/tfbridge/schema.go:975 +0x6ea
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutput({0xe3ddae8?, 0xc0029fc780?}, {0xb3a2ce0?, 0xc004fe9170?}, {0xe3e03a0?, 0xc000e58b40?}, 0xc004ffb6e0?, 0xb3a2ce0?, 0x8?, 0x1)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.36.0/pkg/tfbridge/schema.go:983 +0x70
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutputs({0xe3ddae8, 0xc0029fc780}, 0xc000e4d5e0?, {0xe3bfd08, 0xc000e31350}, 0x98?, 0xc004fe9320?, 0x20?, 0x93?)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.36.0/pkg/tfbridge/schema.go:856 +0x174
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutput.func1({0xe3ddae8, 0xc0029fc780}, {0xb3a2ce0, 0xc004fe9140}, {0xe3e02e0, 0xc004ee9e00}, 0x0, 0xc004fe90e0, 0x0, 0x1)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.36.0/pkg/tfbridge/schema.go:975 +0x6ea
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutput({0xe3ddae8?, 0xc0029fc780?}, {0xb3a2ce0?, 0xc004fe9140?}, {0xe3e02e0?, 0xc004ee9e00?}, 0x1?, 0x1?, 0x10?, 0x1)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.36.0/pkg/tfbridge/schema.go:983 +0x70
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutput.func1({0xe3ddae8, 0xc0029fc780}, {0xa5ee6a0, 0xc004fe66c0}, {0xe3e03a0, 0xc000e58c80}, 0x0, 0xc004fe90e0, 0x0, 0x1)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.36.0/pkg/tfbridge/schema.go:944 +0xb65
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutput({0xe3ddae8?, 0xc0029fc780?}, {0xa5ee6a0?, 0xc004fe66c0?}, {0xe3e03a0?, 0xc000e58c80?}, 0xc0009e0b60?, 0xc0009e0b8b?, 0xc8?, 0x1)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.36.0/pkg/tfbridge/schema.go:983 +0x70
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutputs({0xe3ddae8, 0xc0029fc780}, 0xc002a72f00?, {0xe3bfd08, 0xc000e31140}, 0xc002a394d0?, 0xe3c1f40?, 0xa0?, 0xd7?)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.36.0/pkg/tfbridge/schema.go:856 +0x174
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Check(0xc002a72f00, {0xe3b37e8, 0xc004fe8e40}, 0xc004f40660)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.36.0/pkg/tfbridge/provider.go:731 +0x8ea
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Check_Handler.func1({0xe3b37e8, 0xc004fe8e40}, {0xc811860?, 0xc004f40660})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.50.1/proto/go/provider.pb.go:3879 +0x78
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0xe3b37e8, 0xc004fe8c00}, {0xc811860, 0xc004f40660}, 0xc004fc3e80, 0xc004fe6498)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3f9
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Check_Handler({0xce16c40?, 0xc002a72f00}, {0xe3b37e8, 0xc004fe8c00}, 0xc004fe5180, 0xc002b1a900)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.50.1/proto/go/provider.pb.go:3881 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005f43c0, {0xe3c3ca0, 0xc002aa1380}, 0xc004c1f320, 0xc002b932f0, 0x1691f310, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
    google.golang.org/grpc.(*Server).handleStream(0xc0005f43c0, {0xe3c3ca0, 0xc002aa1380}, 0xc004c1f320, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:965 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:963 +0x28a
 ```

Used packages:
- node @pulumi/pulumi: 3.49.0
- node @pulumi/aws: 5.27.0
- pulumi cli: 3.49.0
- pulumi resource plugin aws: 5.27.0

This happened during refactoring of a large code-base and I can't really pinpoint where or when the error is raised during the deployment. Therefore I'm not able to reproduce this in a small example.

Facts I currently know:
- we use a (node) library which uses an object like this in it's implementation: `{BS_PRIVATE_NESTED_SOME_NONE: 0}`
- [pulumi-terraform-bridge/names.go:31](https://github.com/pulumi/pulumi-terraform-bridge/blob/8373d5d27d7148fd6742cd8e2f006f3d26e0af70/pkg/tfbridge/names.go#L31) transforms a given name like `BS_PRIVATE_NESTED_SOME_NONE` to `b_s__p_r_i_v_a_t_e__n_e_s_t_e_d__s_o_m_e__n_o_n_e`
- [pulumi-terraform-bridge/names.go:83](https://github.com/pulumi/pulumi-terraform-bridge/blob/8373d5d27d7148fd6742cd8e2f006f3d26e0af70/pkg/tfbridge/names.go#L83) chockes on a name given like `b_s__p_r_i_v_a_t_e__n_e_s_t_e_d__s_o_m_e__n_o_n_e` with the observed assertion-failure `Unexpected duplicate underscore`
- this is probably not in relation to setting lambda environment variables with pulumi (which is the only case I found existing issues for describing similar symptoms)

Any suggestion on how I could debug this any further and how to pinpoint when/where this assertion fails during the deployment?

**Comment by AaronFriel** [comment]
Thanks for reporting this!

Coincidentally the panic assertion was removed in a recent release, not yet incorporated into the AWS provider:
- https://github.com/pulumi/pulumi-terraform-bridge/pull/742

And we've also made a series of improvements to the name routine in recent pull requests, we may just need to work with the providers team to repro your bug and see if the recent changes resolve.

**Comment by AaronFriel** [comment]
@woeps could you help us reproduce by finding a minimal program or set of resources that, when you add them to your program, cause the panic?

**Comment by woeps** [comment]
> @woeps could you help us reproduce by finding a minimal program or set of resources that, when you add them to your program, cause the panic?

@AaronFriel I'd like to try, but without any hint on where I should start looking into this, I feel like it would be impossible to find the right combination to repro this issue. - We have a quite complex / large codebase.

Is there any way to get some hint on where or when the assertion fails during a deployment? e.g. trace?

**Comment by AaronFriel** [comment]
@woeps Usually there should be one resource implicated in causing the panic. It'd be helpful if you could list the SDK and provider versions with the output of `pulumi about`.

The fix I applied in #742 requires providers to upgrade to use it, so you may be able to opt in to the fix here by updating the providers without updating `@pulumi/pulumi`.

Regarding your edit: if there's a breaking change in code serialization & you haven't already made an issue, please report this on github.com/pulumi/pulumi! Our customers rely on function serialization and we take breaks seriously. Just to make sure though, can you check to see if you're using Node 19.2 or 19.3? There was an upstream issue in V8 and Node that broke function serialization, and we requested that to be reverted, see:
- https://github.com/pulumi/pulumi/issues/11488

**Comment by woeps** [comment]
@AaronFriel I ran `pulumi about` in the ci pipeline:
```
$ pulumi about
Logging in using access token from PULUMI_ACCESS_TOKEN
CLI          
Version      3.49.0
Go Version   go1.19.3
Go Compiler  gc
Plugins
NAME    VERSION
aws     5.27.0
nodejs  unknown
Host     
OS       debian
Version  11.6
Arch     x86_64
This project is written in nodejs: executable='/usr/local/bin/node' version='v16.19.0'
```

> ... so you may be able to opt in to the fix here by updating the providers without updating @pulumi/pulumi.

That's good to know! I wasn't quite sure, how independent these two packages were.

PS: I updated my [previous message](https://github.com/pulumi/pulumi-terraform-bridge/issues/62#issuecomment-1413508521) containing the pasted error message to include all of the "diagnostics" message. I guess `aws:appsync:GraphQLApi` means this resource is supposed to be the "culprit"? I will look into more throroughly next week. (after testing a workaround to unblock us: renaming all js object property occurence to lower-case)

**Comment by iwahbe** [comment]
Given the age of the issue, the fact that the triggering assert is no longer present in our code base (and we have completely rewritten the relevant function), and the lack of a reproduction, and that there has been no new information in the last 4 months, I'm going to close as no-repro.

If you see this issue again, please re-open this issue or raise a fresh issue.
