### ISSUE TITLE
panic: nil pointer on pulumi up with experimental Plugin Framework resource

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#969]
### What happened?

The issue arose on an experimental build of pulumi-aws where some of the resources are served via Plugin Framework. 

pulumi preview succeeds and pulumi up does not.

```
name: check
runtime: yaml
description: A minimal Pulumi YAML program
outputs: {}
resources:
  bucket1:
    type: aws:s3:Bucket
  # rexpl1:
  #   type: aws:resourceexplorer/index:Index
  #   properties:
  #     type: LOCAL
  cidrcol1:
    type: aws:route53/cidrCollection:CidrCollection
    properties:
     name: collection-1
variables: {}
```

```
t0yv0@Antons-MacBook-Pro> pulumi up --yes                                                                                                                                                            ~/code/pulumi-aws/check
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/t0yv0/check/dev/previews/387cd37f-b77b-4cf3-af65-a0198cb7271b

     Type                           Name       Plan       
     pulumi:pulumi:Stack            check-dev             
 +   ├─ aws:route53:CidrCollection  cidrcol1   create     
 +   └─ aws:s3:Bucket               bucket1    create     


Resources:
    + 2 to create
    1 unchanged

Updating (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/t0yv0/check/dev/updates/2

     Type                           Name       Status                  Info
     pulumi:pulumi:Stack            check-dev  **failed**              1 error; 19 messages
 +   ├─ aws:route53:CidrCollection  cidrcol1   **creating failed**     1 error
 +   └─ aws:s3:Bucket               bucket1    **creating failed**     1 error


Diagnostics:
  pulumi:pulumi:Stack (check-dev):
    error: update failed

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x813d829]
    goroutine 135 [running]:
    github.com/aws/aws-sdk-go/service/route53.(*Route53).newRequest(0x0?, 0xc008e22c80?, {0xd8afea0?, 0xc00a4056b0?}, {0xd6883e0?, 0xc00a405760?})
        /Users/t0yv0/go/pkg/mod/github.com/aws/aws-sdk-go@v1.44.226/service/route53/service.go:96 +0x49
    github.com/aws/aws-sdk-go/service/route53.(*Route53).CreateCidrCollectionRequest(0x1?, 0xc00a4056b0)
        /Users/t0yv0/go/pkg/mod/github.com/aws/aws-sdk-go@v1.44.226/service/route53/api.go:695 +0xc5
    github.com/aws/aws-sdk-go/service/route53.(*Route53).CreateCidrCollectionWithContext(0x1000001014ea0?, {0xffb3570, 0xc013769230}, 0xc01372fd80?, {0x0, 0x0, 0xffffffffffffffff?})
        /Users/t0yv0/go/pkg/mod/github.com/aws/aws-sdk-go@v1.44.226/service/route53/api.go:745 +0x34
    github.com/hashicorp/terraform-provider-aws/internal/service/route53.(*resourceCIDRCollection).Create.func1()
        /Users/t0yv0/code/pulumi-aws/upstream/internal/service/route53/cidr_collection.go:82 +0x31
    github.com/hashicorp/terraform-provider-aws/internal/tfresource.RetryWhen.func1()
        /Users/t0yv0/code/pulumi-aws/upstream/internal/tfresource/retry.go:30 +0x36
    github.com/hashicorp/terraform-provider-aws/internal/tfresource.Retry.func1()
        /Users/t0yv0/code/pulumi-aws/upstream/internal/tfresource/retry.go:215 +0x56
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext.func1()
        /Users/t0yv0/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20220824175045-450992f2f5b9/helper/resource/state.go:110 +0x1c4
    created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext
        /Users/t0yv0/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20220824175045-450992f2f5b9/helper/resource/state.go:83 +0x1d8

  aws:route53:CidrCollection (cidrcol1):
    error: error reading from server: EOF

  aws:s3:Bucket (bucket1):
    error: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:55860: connect: connection refused"

Resources:
    1 unchanged

Duration: 4s

warning: A new version of Pulumi is available. To upgrade from version '3.60.1' to '3.61.1', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
```

Possibly related to needing to support ProviderMeta feature correctly in the framework bridge.

### Expected Behavior

NA

### Steps to reproduce

NA

### Output of `pulumi about`

NA

### Additional context

NA

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi-terraform-bridge/issues/794 related.

**Comment by t0yv0** [comment]
I was able to get this fixed without any changes to Plugin Framework code.

The PR is at:

https://github.com/pulumi/pulumi-aws/pull/2453

The key change is to share the provider object when shimming and make sure that only one object not more are created. This is important because the object state is used to propagate data from provider Configure call to per-resource Configure call in the framework, but AWS provider only implements Configure hooks using SDKV2 API. 

So when muxer broadcasts Configure call to both SDKV2 provider and PF provider what happens is that if they're distinct objects underneath only the SDKV2 one gets initialized properly (specifically Route53 clients), but if they're a shared object then it gets initialized correctly.

```go
package shim

import (
	"context"

	pfprovider "github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-provider-aws/internal/provider"
	"github.com/hashicorp/terraform-provider-aws/internal/provider/fwprovider"
)

type UpstreamProvider struct {
	SDKV2Provider           *schema.Provider
	PluginFrameworkProvider pfprovider.Provider
}

func NewUpstreamProvider(ctx context.Context) (UpstreamProvider, error) {
	primary, err := provider.New(ctx)
	if err != nil {
		return UpstreamProvider{}, err
	}
	pf := fwprovider.New(primary)
	return UpstreamProvider{
		SDKV2Provider:           primary,
		PluginFrameworkProvider: pf,
	}, nil
}
```
